// Copyright (c) Codesphere Inc.
// SPDX-License-Identifier: Apache-2.0

package main

import (
	"fmt"
	"log"
	"os"
	"strings"
	"time"

	oms "github.com/codesphere-cloud/oms/cli/cmd"
	"github.com/spf13/cobra/doc"
)

func main() {
	// Ensure the generated docs use the stable project command name.
	root := oms.GetRootCmd()
	root.Use = "oms-cli"

	root.DisableAutoGenTag = true

	identity := func(s string) string { return s }
	emptyStr := func(s string) string { return "" }
	now := time.Now().Format("2-Jan-2006")
	err := doc.GenMarkdownTreeCustom(root, "docs", emptyStr, identity)
	if err != nil {
		log.Fatal(err)
	}

	mainDocPath := "docs/oms-cli.md"
	readmePath := "docs/README.md"

	content, err := os.ReadFile(mainDocPath)
	if err != nil {
		log.Fatal(err)
	}

	contentStr := strings.TrimRight(string(content), "\n")
	timestampLine := fmt.Sprintf("\n###### Auto generated by spf13/cobra on %s\n", now)
	contentWithTimestamp := contentStr + timestampLine

	err = os.WriteFile(readmePath, []byte(contentWithTimestamp), 0644)
	if err != nil {
		log.Fatal(err)
	}
}
