// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package github

import (
	"context"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGitHubClient creates a new instance of MockGitHubClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGitHubClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGitHubClient {
	mock := &MockGitHubClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGitHubClient is an autogenerated mock type for the GitHubClient type
type MockGitHubClient struct {
	mock.Mock
}

type MockGitHubClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGitHubClient) EXPECT() *MockGitHubClient_Expecter {
	return &MockGitHubClient_Expecter{mock: &_m.Mock}
}

// GetTeamMemberSSHKeys provides a mock function for the type MockGitHubClient
func (_mock *MockGitHubClient) GetTeamMemberSSHKeys(ctx context.Context, org string, teamSlug string) ([]TeamMemberKeys, error) {
	ret := _mock.Called(ctx, org, teamSlug)

	if len(ret) == 0 {
		panic("no return value specified for GetTeamMemberSSHKeys")
	}

	var r0 []TeamMemberKeys
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]TeamMemberKeys, error)); ok {
		return returnFunc(ctx, org, teamSlug)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []TeamMemberKeys); ok {
		r0 = returnFunc(ctx, org, teamSlug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]TeamMemberKeys)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, org, teamSlug)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGitHubClient_GetTeamMemberSSHKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeamMemberSSHKeys'
type MockGitHubClient_GetTeamMemberSSHKeys_Call struct {
	*mock.Call
}

// GetTeamMemberSSHKeys is a helper method to define mock.On call
//   - ctx context.Context
//   - org string
//   - teamSlug string
func (_e *MockGitHubClient_Expecter) GetTeamMemberSSHKeys(ctx any, org any, teamSlug any) *MockGitHubClient_GetTeamMemberSSHKeys_Call {
	return &MockGitHubClient_GetTeamMemberSSHKeys_Call{Call: _e.mock.On("GetTeamMemberSSHKeys", ctx, org, teamSlug)}
}

func (_c *MockGitHubClient_GetTeamMemberSSHKeys_Call) Run(run func(ctx context.Context, org string, teamSlug string)) *MockGitHubClient_GetTeamMemberSSHKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGitHubClient_GetTeamMemberSSHKeys_Call) Return(teamMemberKeys []TeamMemberKeys, err error) *MockGitHubClient_GetTeamMemberSSHKeys_Call {
	_c.Call.Return(teamMemberKeys, err)
	return _c
}

func (_c *MockGitHubClient_GetTeamMemberSSHKeys_Call) RunAndReturn(run func(ctx context.Context, org string, teamSlug string) ([]TeamMemberKeys, error)) *MockGitHubClient_GetTeamMemberSSHKeys_Call {
	_c.Call.Return(run)
	return _c
}
