version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
    - amd64
    - arm64
    - arm
    main: ./cli
    binary: oms-cli

  - id: service
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
    - amd64
    - arm64
    - arm
    main: ./service
    binary: oms-service

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs"
      - "^test"
      - "^devx"
      - "^chore"

archives:
- formats: binary

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
