# Copyright (c) Codesphere Inc.
# SPDX-License-Identifier: Apache-2.0

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: cli
    env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64
      - linux_arm64
      - darwin_arm64
      - darwin_amd64
      - windows_amd64
    main: ./cli
    binary: oms
    ldflags:
    - -s -w
    - -X github.com/codesphere-cloud/oms/internal/version.version={{.Version}}
    - -X github.com/codesphere-cloud/oms/internal/version.commit={{.Commit}}
    - -X github.com/codesphere-cloud/oms/internal/version.date={{.Date}}
    - -X github.com/codesphere-cloud/oms/internal/version.os={{.Os}}
    - -X github.com/codesphere-cloud/oms/internal/version.arch={{.Arch}}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs"
      - "^test"
      - "^devx"
      - "^chore"

archives:
- id: bin
  formats:
  - binary
- id: tar
  formats:
  - tar.gz
  name_template: "{{.Os}}_{{.Arch}}"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
