version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
    - amd64
    - arm64
    - arm
    main: ./cli
    binary: oms-cli
    ldflags:
    - -s -w
    - -X github.com/codesphere-cloud/oms/internal/version.version={{.Version}}
    - -X github.com/codesphere-cloud/oms/internal/version.commit={{.Commit}}
    - -X github.com/codesphere-cloud/oms/internal/version.date={{.Date}}

  - id: service
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
    - amd64
    - arm64
    - arm
    main: ./service
    binary: oms-service
    ldflags:
    - -s -w
    - -X github.com/codesphere-cloud/oms/internal/version.version={{.Version}}
    - -X github.com/codesphere-cloud/oms/internal/version.commit={{.Commit}}
    - -X github.com/codesphere-cloud/oms/internal/version.date={{.Date}}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs"
      - "^test"
      - "^devx"
      - "^chore"

archives:
- formats:
    - binary
    - tar.gz
  name_template: "{{.Os}}_{{.Arch}}"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
