# Copyright (c) Codesphere Inc.
# SPDX-License-Identifier: Apache-2.0

all: false
dir: "{{.InterfaceDir}}"
force-file-write: true
filename: "mocks.go"
formatter: gofmt
log-level: info
structname: "{{.Mock}}{{.InterfaceName}}"
pkgname: "{{.SrcPackageName}}"
recursive: true
require-template-schema-exists: true
template: testify
template-schema: "{{.Template}}.schema.json"
packages:
  github.com/codesphere-cloud/oms/internal:
  github.com/codesphere-cloud/oms/internal/installer:
  github.com/codesphere-cloud/oms/pkg:
  github.com/codesphere-cloud/oms/cli/cmd:
