// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package docker

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockDockerManager creates a new instance of MockDockerManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDockerManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDockerManager {
	mock := &MockDockerManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDockerManager is an autogenerated mock type for the DockerManager type
type MockDockerManager struct {
	mock.Mock
}

type MockDockerManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDockerManager) EXPECT() *MockDockerManager_Expecter {
	return &MockDockerManager_Expecter{mock: &_m.Mock}
}

// InstallWithApt provides a mock function for the type MockDockerManager
func (_mock *MockDockerManager) InstallWithApt() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for InstallWithApt")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDockerManager_InstallWithApt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InstallWithApt'
type MockDockerManager_InstallWithApt_Call struct {
	*mock.Call
}

// InstallWithApt is a helper method to define mock.On call
func (_e *MockDockerManager_Expecter) InstallWithApt() *MockDockerManager_InstallWithApt_Call {
	return &MockDockerManager_InstallWithApt_Call{Call: _e.mock.On("InstallWithApt")}
}

func (_c *MockDockerManager_InstallWithApt_Call) Run(run func()) *MockDockerManager_InstallWithApt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDockerManager_InstallWithApt_Call) Return(err error) *MockDockerManager_InstallWithApt_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDockerManager_InstallWithApt_Call) RunAndReturn(run func() error) *MockDockerManager_InstallWithApt_Call {
	_c.Call.Return(run)
	return _c
}

// IsInstalled provides a mock function for the type MockDockerManager
func (_mock *MockDockerManager) IsInstalled() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsInstalled")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockDockerManager_IsInstalled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsInstalled'
type MockDockerManager_IsInstalled_Call struct {
	*mock.Call
}

// IsInstalled is a helper method to define mock.On call
func (_e *MockDockerManager_Expecter) IsInstalled() *MockDockerManager_IsInstalled_Call {
	return &MockDockerManager_IsInstalled_Call{Call: _e.mock.On("IsInstalled")}
}

func (_c *MockDockerManager_IsInstalled_Call) Run(run func()) *MockDockerManager_IsInstalled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDockerManager_IsInstalled_Call) Return(b bool) *MockDockerManager_IsInstalled_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockDockerManager_IsInstalled_Call) RunAndReturn(run func() bool) *MockDockerManager_IsInstalled_Call {
	_c.Call.Return(run)
	return _c
}
