// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package docker

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockDockerInstaller creates a new instance of MockDockerInstaller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDockerInstaller(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDockerInstaller {
	mock := &MockDockerInstaller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDockerInstaller is an autogenerated mock type for the DockerInstaller type
type MockDockerInstaller struct {
	mock.Mock
}

type MockDockerInstaller_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDockerInstaller) EXPECT() *MockDockerInstaller_Expecter {
	return &MockDockerInstaller_Expecter{mock: &_m.Mock}
}

// Install provides a mock function for the type MockDockerInstaller
func (_mock *MockDockerInstaller) Install() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Install")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDockerInstaller_Install_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Install'
type MockDockerInstaller_Install_Call struct {
	*mock.Call
}

// Install is a helper method to define mock.On call
func (_e *MockDockerInstaller_Expecter) Install() *MockDockerInstaller_Install_Call {
	return &MockDockerInstaller_Install_Call{Call: _e.mock.On("Install")}
}

func (_c *MockDockerInstaller_Install_Call) Run(run func()) *MockDockerInstaller_Install_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDockerInstaller_Install_Call) Return(err error) *MockDockerInstaller_Install_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDockerInstaller_Install_Call) RunAndReturn(run func() error) *MockDockerInstaller_Install_Call {
	_c.Call.Return(run)
	return _c
}

// IsInstalled provides a mock function for the type MockDockerInstaller
func (_mock *MockDockerInstaller) IsInstalled() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsInstalled")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockDockerInstaller_IsInstalled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsInstalled'
type MockDockerInstaller_IsInstalled_Call struct {
	*mock.Call
}

// IsInstalled is a helper method to define mock.On call
func (_e *MockDockerInstaller_Expecter) IsInstalled() *MockDockerInstaller_IsInstalled_Call {
	return &MockDockerInstaller_IsInstalled_Call{Call: _e.mock.On("IsInstalled")}
}

func (_c *MockDockerInstaller_IsInstalled_Call) Run(run func()) *MockDockerInstaller_IsInstalled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDockerInstaller_IsInstalled_Call) Return(b bool) *MockDockerInstaller_IsInstalled_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockDockerInstaller_IsInstalled_Call) RunAndReturn(run func() bool) *MockDockerInstaller_IsInstalled_Call {
	_c.Call.Return(run)
	return _c
}
