// Copyright (c) Codesphere Inc.
// SPDX-License-Identifier: Apache-2.0

package vault

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/codesphere-cloud/oms/internal/installer/files"
	"github.com/codesphere-cloud/oms/internal/util"
	sopsage "github.com/getsops/sops/v3/age"
)

// Type identifies the on-disk vault format.
type Type string

// Supported Vault types
const (
	TypeSOPS    Type = "sops"
	TypePlain   Type = "plain"
	DefaultType      = TypeSOPS
)

// Vault is the persistence boundary for installer secrets. Callers work with
// InstallVault values and do not need to know how those values are represented
// or protected on disk.
type Vault interface {
	Load() (*files.InstallVault, error)
	LoadOrCreate() (*files.InstallVault, error)
	Save(*files.InstallVault) error
}

// Options contains the parameters currently accepted by the vault factory.
// The factory only forwards file parameters to implementations that use them;
// future non-file vaults can ignore Path and WithComments entirely.
type Options struct {
	Path         string
	AgeKey       string
	WithComments bool
	FileIO       util.FileIO
}

// FileOptions contains configuration shared by file-backed vaults. It is kept
// out of the Vault interface so non-file implementations do not inherit file
// concepts.
type FileOptions struct {
	Path         string
	WithComments bool
	FileIO       util.FileIO
}

// ParseType validates a user supplied vault type.
func ParseType(value string) (Type, error) {
	switch Type(strings.ToLower(strings.TrimSpace(value))) {
	case "", TypeSOPS:
		return TypeSOPS, nil
	case TypePlain:
		return TypePlain, nil
	default:
		return "", fmt.Errorf("unsupported vault type %q (must be %q or %q)", value, TypeSOPS, TypePlain)
	}
}

// ValidateConfiguration validates backend-specific, non-resource parameters.
// File paths are intentionally validated by the file-backed constructors.
func ValidateConfiguration(vaultType Type, ageKey string) error {
	if vaultType != TypeSOPS {
		return nil
	}

	if ageKey != "" || os.Getenv(sopsage.SopsAgeKeyEnv) != "" || os.Getenv(sopsage.SopsAgeKeyFileEnv) != "" {
		return nil
	}

	return fmt.Errorf("SOPS vault requires an age key; set an age key argument or %s/%s", sopsage.SopsAgeKeyEnv, sopsage.SopsAgeKeyFileEnv)
}

// New creates a vault implementation for the requested type.
func New(vaultType Type, opts Options) (Vault, error) {
	switch vaultType {
	case TypeSOPS:
		return NewSOPSVault(SOPSOptions{
			File:   FileOptions{Path: opts.Path, WithComments: opts.WithComments, FileIO: opts.FileIO},
			AgeKey: opts.AgeKey,
		})
	case TypePlain:
		return NewPlainFileVault(FileOptions{Path: opts.Path, WithComments: opts.WithComments, FileIO: opts.FileIO})
	default:
		return nil, fmt.Errorf("unsupported vault type %q", vaultType)
	}
}

// NewFromString parses vaultType and creates the matching implementation.
func NewFromString(vaultType string, opts Options) (Vault, error) {
	t, err := ParseType(vaultType)
	if err != nil {
		return nil, err
	}

	return New(t, opts)
}

func marshalVault(data *files.InstallVault, comments bool) ([]byte, error) {
	if data == nil {
		data = &files.InstallVault{}
	}

	plain, err := data.Marshal()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal vault: %w", err)
	}

	if comments {
		plain = append([]byte("# Codesphere Installer Secrets\n# Generated by OMS CLI\n\n"), plain...)
	}

	return plain, nil
}

func fileIOOrDefault(fileIO util.FileIO) util.FileIO {
	if fileIO != nil {
		return fileIO
	}

	return util.NewFilesystemWriter()
}

func writeVaultFile(fileIO util.FileIO, path string, data []byte) error {
	if err := fileIO.MkdirAll(filepath.Dir(path), 0700); err != nil {
		return fmt.Errorf("failed to create vault directory: %w", err)
	}

	tmpPath, err := fileIO.CreateTemp(filepath.Dir(path), ".vault-*")
	if err != nil {
		return fmt.Errorf("failed to create temporary vault: %w", err)
	}
	defer func() { _ = fileIO.Remove(tmpPath) }()

	if err := fileIO.WriteFile(tmpPath, data, 0600); err != nil {
		return fmt.Errorf("failed to write vault: %w", err)
	}

	if err := fileIO.Rename(tmpPath, path); err != nil {
		return fmt.Errorf("failed to replace vault: %w", err)
	}

	return nil
}
