// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package installer

import (
	"github.com/codesphere-cloud/oms/internal/installer/files"
	"github.com/codesphere-cloud/oms/internal/util"
	mock "github.com/stretchr/testify/mock"
)

// NewMockConfigManager creates a new instance of MockConfigManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfigManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfigManager {
	mock := &MockConfigManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConfigManager is an autogenerated mock type for the ConfigManager type
type MockConfigManager struct {
	mock.Mock
}

type MockConfigManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfigManager) EXPECT() *MockConfigManager_Expecter {
	return &MockConfigManager_Expecter{mock: &_m.Mock}
}

// ParseConfigYaml provides a mock function for the type MockConfigManager
func (_mock *MockConfigManager) ParseConfigYaml(configPath string) (files.RootConfig, error) {
	ret := _mock.Called(configPath)

	if len(ret) == 0 {
		panic("no return value specified for ParseConfigYaml")
	}

	var r0 files.RootConfig
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (files.RootConfig, error)); ok {
		return returnFunc(configPath)
	}
	if returnFunc, ok := ret.Get(0).(func(string) files.RootConfig); ok {
		r0 = returnFunc(configPath)
	} else {
		r0 = ret.Get(0).(files.RootConfig)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(configPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConfigManager_ParseConfigYaml_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseConfigYaml'
type MockConfigManager_ParseConfigYaml_Call struct {
	*mock.Call
}

// ParseConfigYaml is a helper method to define mock.On call
//   - configPath string
func (_e *MockConfigManager_Expecter) ParseConfigYaml(configPath interface{}) *MockConfigManager_ParseConfigYaml_Call {
	return &MockConfigManager_ParseConfigYaml_Call{Call: _e.mock.On("ParseConfigYaml", configPath)}
}

func (_c *MockConfigManager_ParseConfigYaml_Call) Run(run func(configPath string)) *MockConfigManager_ParseConfigYaml_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConfigManager_ParseConfigYaml_Call) Return(rootConfig files.RootConfig, err error) *MockConfigManager_ParseConfigYaml_Call {
	_c.Call.Return(rootConfig, err)
	return _c
}

func (_c *MockConfigManager_ParseConfigYaml_Call) RunAndReturn(run func(configPath string) (files.RootConfig, error)) *MockConfigManager_ParseConfigYaml_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInstallConfigManager creates a new instance of MockInstallConfigManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInstallConfigManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInstallConfigManager {
	mock := &MockInstallConfigManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInstallConfigManager is an autogenerated mock type for the InstallConfigManager type
type MockInstallConfigManager struct {
	mock.Mock
}

type MockInstallConfigManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInstallConfigManager) EXPECT() *MockInstallConfigManager_Expecter {
	return &MockInstallConfigManager_Expecter{mock: &_m.Mock}
}

// ApplyProfile provides a mock function for the type MockInstallConfigManager
func (_mock *MockInstallConfigManager) ApplyProfile(profile string) error {
	ret := _mock.Called(profile)

	if len(ret) == 0 {
		panic("no return value specified for ApplyProfile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(profile)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInstallConfigManager_ApplyProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyProfile'
type MockInstallConfigManager_ApplyProfile_Call struct {
	*mock.Call
}

// ApplyProfile is a helper method to define mock.On call
//   - profile string
func (_e *MockInstallConfigManager_Expecter) ApplyProfile(profile interface{}) *MockInstallConfigManager_ApplyProfile_Call {
	return &MockInstallConfigManager_ApplyProfile_Call{Call: _e.mock.On("ApplyProfile", profile)}
}

func (_c *MockInstallConfigManager_ApplyProfile_Call) Run(run func(profile string)) *MockInstallConfigManager_ApplyProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockInstallConfigManager_ApplyProfile_Call) Return(err error) *MockInstallConfigManager_ApplyProfile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInstallConfigManager_ApplyProfile_Call) RunAndReturn(run func(profile string) error) *MockInstallConfigManager_ApplyProfile_Call {
	_c.Call.Return(run)
	return _c
}

// CollectInteractively provides a mock function for the type MockInstallConfigManager
func (_mock *MockInstallConfigManager) CollectInteractively() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CollectInteractively")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInstallConfigManager_CollectInteractively_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CollectInteractively'
type MockInstallConfigManager_CollectInteractively_Call struct {
	*mock.Call
}

// CollectInteractively is a helper method to define mock.On call
func (_e *MockInstallConfigManager_Expecter) CollectInteractively() *MockInstallConfigManager_CollectInteractively_Call {
	return &MockInstallConfigManager_CollectInteractively_Call{Call: _e.mock.On("CollectInteractively")}
}

func (_c *MockInstallConfigManager_CollectInteractively_Call) Run(run func()) *MockInstallConfigManager_CollectInteractively_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockInstallConfigManager_CollectInteractively_Call) Return(err error) *MockInstallConfigManager_CollectInteractively_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInstallConfigManager_CollectInteractively_Call) RunAndReturn(run func() error) *MockInstallConfigManager_CollectInteractively_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateSecrets provides a mock function for the type MockInstallConfigManager
func (_mock *MockInstallConfigManager) GenerateSecrets() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GenerateSecrets")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInstallConfigManager_GenerateSecrets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateSecrets'
type MockInstallConfigManager_GenerateSecrets_Call struct {
	*mock.Call
}

// GenerateSecrets is a helper method to define mock.On call
func (_e *MockInstallConfigManager_Expecter) GenerateSecrets() *MockInstallConfigManager_GenerateSecrets_Call {
	return &MockInstallConfigManager_GenerateSecrets_Call{Call: _e.mock.On("GenerateSecrets")}
}

func (_c *MockInstallConfigManager_GenerateSecrets_Call) Run(run func()) *MockInstallConfigManager_GenerateSecrets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockInstallConfigManager_GenerateSecrets_Call) Return(err error) *MockInstallConfigManager_GenerateSecrets_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInstallConfigManager_GenerateSecrets_Call) RunAndReturn(run func() error) *MockInstallConfigManager_GenerateSecrets_Call {
	_c.Call.Return(run)
	return _c
}

// GetInstallConfig provides a mock function for the type MockInstallConfigManager
func (_mock *MockInstallConfigManager) GetInstallConfig() *files.RootConfig {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetInstallConfig")
	}

	var r0 *files.RootConfig
	if returnFunc, ok := ret.Get(0).(func() *files.RootConfig); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*files.RootConfig)
		}
	}
	return r0
}

// MockInstallConfigManager_GetInstallConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInstallConfig'
type MockInstallConfigManager_GetInstallConfig_Call struct {
	*mock.Call
}

// GetInstallConfig is a helper method to define mock.On call
func (_e *MockInstallConfigManager_Expecter) GetInstallConfig() *MockInstallConfigManager_GetInstallConfig_Call {
	return &MockInstallConfigManager_GetInstallConfig_Call{Call: _e.mock.On("GetInstallConfig")}
}

func (_c *MockInstallConfigManager_GetInstallConfig_Call) Run(run func()) *MockInstallConfigManager_GetInstallConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockInstallConfigManager_GetInstallConfig_Call) Return(rootConfig *files.RootConfig) *MockInstallConfigManager_GetInstallConfig_Call {
	_c.Call.Return(rootConfig)
	return _c
}

func (_c *MockInstallConfigManager_GetInstallConfig_Call) RunAndReturn(run func() *files.RootConfig) *MockInstallConfigManager_GetInstallConfig_Call {
	_c.Call.Return(run)
	return _c
}

// GetVault provides a mock function for the type MockInstallConfigManager
func (_mock *MockInstallConfigManager) GetVault() *files.InstallVault {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetVault")
	}

	var r0 *files.InstallVault
	if returnFunc, ok := ret.Get(0).(func() *files.InstallVault); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*files.InstallVault)
		}
	}
	return r0
}

// MockInstallConfigManager_GetVault_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVault'
type MockInstallConfigManager_GetVault_Call struct {
	*mock.Call
}

// GetVault is a helper method to define mock.On call
func (_e *MockInstallConfigManager_Expecter) GetVault() *MockInstallConfigManager_GetVault_Call {
	return &MockInstallConfigManager_GetVault_Call{Call: _e.mock.On("GetVault")}
}

func (_c *MockInstallConfigManager_GetVault_Call) Run(run func()) *MockInstallConfigManager_GetVault_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockInstallConfigManager_GetVault_Call) Return(installVault *files.InstallVault) *MockInstallConfigManager_GetVault_Call {
	_c.Call.Return(installVault)
	return _c
}

func (_c *MockInstallConfigManager_GetVault_Call) RunAndReturn(run func() *files.InstallVault) *MockInstallConfigManager_GetVault_Call {
	_c.Call.Return(run)
	return _c
}

// LoadInstallConfigFromFile provides a mock function for the type MockInstallConfigManager
func (_mock *MockInstallConfigManager) LoadInstallConfigFromFile(configPath string) error {
	ret := _mock.Called(configPath)

	if len(ret) == 0 {
		panic("no return value specified for LoadInstallConfigFromFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(configPath)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInstallConfigManager_LoadInstallConfigFromFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadInstallConfigFromFile'
type MockInstallConfigManager_LoadInstallConfigFromFile_Call struct {
	*mock.Call
}

// LoadInstallConfigFromFile is a helper method to define mock.On call
//   - configPath string
func (_e *MockInstallConfigManager_Expecter) LoadInstallConfigFromFile(configPath interface{}) *MockInstallConfigManager_LoadInstallConfigFromFile_Call {
	return &MockInstallConfigManager_LoadInstallConfigFromFile_Call{Call: _e.mock.On("LoadInstallConfigFromFile", configPath)}
}

func (_c *MockInstallConfigManager_LoadInstallConfigFromFile_Call) Run(run func(configPath string)) *MockInstallConfigManager_LoadInstallConfigFromFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockInstallConfigManager_LoadInstallConfigFromFile_Call) Return(err error) *MockInstallConfigManager_LoadInstallConfigFromFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInstallConfigManager_LoadInstallConfigFromFile_Call) RunAndReturn(run func(configPath string) error) *MockInstallConfigManager_LoadInstallConfigFromFile_Call {
	_c.Call.Return(run)
	return _c
}

// LoadVaultFromFile provides a mock function for the type MockInstallConfigManager
func (_mock *MockInstallConfigManager) LoadVaultFromFile(vaultPath string) error {
	ret := _mock.Called(vaultPath)

	if len(ret) == 0 {
		panic("no return value specified for LoadVaultFromFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(vaultPath)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInstallConfigManager_LoadVaultFromFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadVaultFromFile'
type MockInstallConfigManager_LoadVaultFromFile_Call struct {
	*mock.Call
}

// LoadVaultFromFile is a helper method to define mock.On call
//   - vaultPath string
func (_e *MockInstallConfigManager_Expecter) LoadVaultFromFile(vaultPath interface{}) *MockInstallConfigManager_LoadVaultFromFile_Call {
	return &MockInstallConfigManager_LoadVaultFromFile_Call{Call: _e.mock.On("LoadVaultFromFile", vaultPath)}
}

func (_c *MockInstallConfigManager_LoadVaultFromFile_Call) Run(run func(vaultPath string)) *MockInstallConfigManager_LoadVaultFromFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockInstallConfigManager_LoadVaultFromFile_Call) Return(err error) *MockInstallConfigManager_LoadVaultFromFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInstallConfigManager_LoadVaultFromFile_Call) RunAndReturn(run func(vaultPath string) error) *MockInstallConfigManager_LoadVaultFromFile_Call {
	_c.Call.Return(run)
	return _c
}

// MergeVaultIntoConfig provides a mock function for the type MockInstallConfigManager
func (_mock *MockInstallConfigManager) MergeVaultIntoConfig() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for MergeVaultIntoConfig")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInstallConfigManager_MergeVaultIntoConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MergeVaultIntoConfig'
type MockInstallConfigManager_MergeVaultIntoConfig_Call struct {
	*mock.Call
}

// MergeVaultIntoConfig is a helper method to define mock.On call
func (_e *MockInstallConfigManager_Expecter) MergeVaultIntoConfig() *MockInstallConfigManager_MergeVaultIntoConfig_Call {
	return &MockInstallConfigManager_MergeVaultIntoConfig_Call{Call: _e.mock.On("MergeVaultIntoConfig")}
}

func (_c *MockInstallConfigManager_MergeVaultIntoConfig_Call) Run(run func()) *MockInstallConfigManager_MergeVaultIntoConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockInstallConfigManager_MergeVaultIntoConfig_Call) Return(err error) *MockInstallConfigManager_MergeVaultIntoConfig_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInstallConfigManager_MergeVaultIntoConfig_Call) RunAndReturn(run func() error) *MockInstallConfigManager_MergeVaultIntoConfig_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateInstallConfig provides a mock function for the type MockInstallConfigManager
func (_mock *MockInstallConfigManager) ValidateInstallConfig() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ValidateInstallConfig")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockInstallConfigManager_ValidateInstallConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateInstallConfig'
type MockInstallConfigManager_ValidateInstallConfig_Call struct {
	*mock.Call
}

// ValidateInstallConfig is a helper method to define mock.On call
func (_e *MockInstallConfigManager_Expecter) ValidateInstallConfig() *MockInstallConfigManager_ValidateInstallConfig_Call {
	return &MockInstallConfigManager_ValidateInstallConfig_Call{Call: _e.mock.On("ValidateInstallConfig")}
}

func (_c *MockInstallConfigManager_ValidateInstallConfig_Call) Run(run func()) *MockInstallConfigManager_ValidateInstallConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockInstallConfigManager_ValidateInstallConfig_Call) Return(strings []string) *MockInstallConfigManager_ValidateInstallConfig_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockInstallConfigManager_ValidateInstallConfig_Call) RunAndReturn(run func() []string) *MockInstallConfigManager_ValidateInstallConfig_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateVault provides a mock function for the type MockInstallConfigManager
func (_mock *MockInstallConfigManager) ValidateVault() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ValidateVault")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockInstallConfigManager_ValidateVault_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateVault'
type MockInstallConfigManager_ValidateVault_Call struct {
	*mock.Call
}

// ValidateVault is a helper method to define mock.On call
func (_e *MockInstallConfigManager_Expecter) ValidateVault() *MockInstallConfigManager_ValidateVault_Call {
	return &MockInstallConfigManager_ValidateVault_Call{Call: _e.mock.On("ValidateVault")}
}

func (_c *MockInstallConfigManager_ValidateVault_Call) Run(run func()) *MockInstallConfigManager_ValidateVault_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockInstallConfigManager_ValidateVault_Call) Return(strings []string) *MockInstallConfigManager_ValidateVault_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockInstallConfigManager_ValidateVault_Call) RunAndReturn(run func() []string) *MockInstallConfigManager_ValidateVault_Call {
	_c.Call.Return(run)
	return _c
}

// WriteInstallConfig provides a mock function for the type MockInstallConfigManager
func (_mock *MockInstallConfigManager) WriteInstallConfig(configPath string, withComments bool) error {
	ret := _mock.Called(configPath, withComments)

	if len(ret) == 0 {
		panic("no return value specified for WriteInstallConfig")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, bool) error); ok {
		r0 = returnFunc(configPath, withComments)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInstallConfigManager_WriteInstallConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteInstallConfig'
type MockInstallConfigManager_WriteInstallConfig_Call struct {
	*mock.Call
}

// WriteInstallConfig is a helper method to define mock.On call
//   - configPath string
//   - withComments bool
func (_e *MockInstallConfigManager_Expecter) WriteInstallConfig(configPath interface{}, withComments interface{}) *MockInstallConfigManager_WriteInstallConfig_Call {
	return &MockInstallConfigManager_WriteInstallConfig_Call{Call: _e.mock.On("WriteInstallConfig", configPath, withComments)}
}

func (_c *MockInstallConfigManager_WriteInstallConfig_Call) Run(run func(configPath string, withComments bool)) *MockInstallConfigManager_WriteInstallConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockInstallConfigManager_WriteInstallConfig_Call) Return(err error) *MockInstallConfigManager_WriteInstallConfig_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInstallConfigManager_WriteInstallConfig_Call) RunAndReturn(run func(configPath string, withComments bool) error) *MockInstallConfigManager_WriteInstallConfig_Call {
	_c.Call.Return(run)
	return _c
}

// WriteVault provides a mock function for the type MockInstallConfigManager
func (_mock *MockInstallConfigManager) WriteVault(vaultPath string, withComments bool) error {
	ret := _mock.Called(vaultPath, withComments)

	if len(ret) == 0 {
		panic("no return value specified for WriteVault")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, bool) error); ok {
		r0 = returnFunc(vaultPath, withComments)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInstallConfigManager_WriteVault_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteVault'
type MockInstallConfigManager_WriteVault_Call struct {
	*mock.Call
}

// WriteVault is a helper method to define mock.On call
//   - vaultPath string
//   - withComments bool
func (_e *MockInstallConfigManager_Expecter) WriteVault(vaultPath interface{}, withComments interface{}) *MockInstallConfigManager_WriteVault_Call {
	return &MockInstallConfigManager_WriteVault_Call{Call: _e.mock.On("WriteVault", vaultPath, withComments)}
}

func (_c *MockInstallConfigManager_WriteVault_Call) Run(run func(vaultPath string, withComments bool)) *MockInstallConfigManager_WriteVault_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockInstallConfigManager_WriteVault_Call) Return(err error) *MockInstallConfigManager_WriteVault_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInstallConfigManager_WriteVault_Call) RunAndReturn(run func(vaultPath string, withComments bool) error) *MockInstallConfigManager_WriteVault_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockK0sManager creates a new instance of MockK0sManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockK0sManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockK0sManager {
	mock := &MockK0sManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockK0sManager is an autogenerated mock type for the K0sManager type
type MockK0sManager struct {
	mock.Mock
}

type MockK0sManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockK0sManager) EXPECT() *MockK0sManager_Expecter {
	return &MockK0sManager_Expecter{mock: &_m.Mock}
}

// Download provides a mock function for the type MockK0sManager
func (_mock *MockK0sManager) Download(version string, force bool, quiet bool) (string, error) {
	ret := _mock.Called(version, force, quiet)

	if len(ret) == 0 {
		panic("no return value specified for Download")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, bool, bool) (string, error)); ok {
		return returnFunc(version, force, quiet)
	}
	if returnFunc, ok := ret.Get(0).(func(string, bool, bool) string); ok {
		r0 = returnFunc(version, force, quiet)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, bool, bool) error); ok {
		r1 = returnFunc(version, force, quiet)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockK0sManager_Download_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Download'
type MockK0sManager_Download_Call struct {
	*mock.Call
}

// Download is a helper method to define mock.On call
//   - version string
//   - force bool
//   - quiet bool
func (_e *MockK0sManager_Expecter) Download(version interface{}, force interface{}, quiet interface{}) *MockK0sManager_Download_Call {
	return &MockK0sManager_Download_Call{Call: _e.mock.On("Download", version, force, quiet)}
}

func (_c *MockK0sManager_Download_Call) Run(run func(version string, force bool, quiet bool)) *MockK0sManager_Download_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockK0sManager_Download_Call) Return(s string, err error) *MockK0sManager_Download_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockK0sManager_Download_Call) RunAndReturn(run func(version string, force bool, quiet bool) (string, error)) *MockK0sManager_Download_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestVersion provides a mock function for the type MockK0sManager
func (_mock *MockK0sManager) GetLatestVersion() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLatestVersion")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockK0sManager_GetLatestVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestVersion'
type MockK0sManager_GetLatestVersion_Call struct {
	*mock.Call
}

// GetLatestVersion is a helper method to define mock.On call
func (_e *MockK0sManager_Expecter) GetLatestVersion() *MockK0sManager_GetLatestVersion_Call {
	return &MockK0sManager_GetLatestVersion_Call{Call: _e.mock.On("GetLatestVersion")}
}

func (_c *MockK0sManager_GetLatestVersion_Call) Run(run func()) *MockK0sManager_GetLatestVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockK0sManager_GetLatestVersion_Call) Return(s string, err error) *MockK0sManager_GetLatestVersion_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockK0sManager_GetLatestVersion_Call) RunAndReturn(run func() (string, error)) *MockK0sManager_GetLatestVersion_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockK0sctlManager creates a new instance of MockK0sctlManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockK0sctlManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockK0sctlManager {
	mock := &MockK0sctlManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockK0sctlManager is an autogenerated mock type for the K0sctlManager type
type MockK0sctlManager struct {
	mock.Mock
}

type MockK0sctlManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockK0sctlManager) EXPECT() *MockK0sctlManager_Expecter {
	return &MockK0sctlManager_Expecter{mock: &_m.Mock}
}

// Apply provides a mock function for the type MockK0sctlManager
func (_mock *MockK0sctlManager) Apply(configPath string, k0sctlPath string, force bool) error {
	ret := _mock.Called(configPath, k0sctlPath, force)

	if len(ret) == 0 {
		panic("no return value specified for Apply")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, bool) error); ok {
		r0 = returnFunc(configPath, k0sctlPath, force)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockK0sctlManager_Apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Apply'
type MockK0sctlManager_Apply_Call struct {
	*mock.Call
}

// Apply is a helper method to define mock.On call
//   - configPath string
//   - k0sctlPath string
//   - force bool
func (_e *MockK0sctlManager_Expecter) Apply(configPath interface{}, k0sctlPath interface{}, force interface{}) *MockK0sctlManager_Apply_Call {
	return &MockK0sctlManager_Apply_Call{Call: _e.mock.On("Apply", configPath, k0sctlPath, force)}
}

func (_c *MockK0sctlManager_Apply_Call) Run(run func(configPath string, k0sctlPath string, force bool)) *MockK0sctlManager_Apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockK0sctlManager_Apply_Call) Return(err error) *MockK0sctlManager_Apply_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockK0sctlManager_Apply_Call) RunAndReturn(run func(configPath string, k0sctlPath string, force bool) error) *MockK0sctlManager_Apply_Call {
	_c.Call.Return(run)
	return _c
}

// Download provides a mock function for the type MockK0sctlManager
func (_mock *MockK0sctlManager) Download(version string, force bool, quiet bool) (string, error) {
	ret := _mock.Called(version, force, quiet)

	if len(ret) == 0 {
		panic("no return value specified for Download")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, bool, bool) (string, error)); ok {
		return returnFunc(version, force, quiet)
	}
	if returnFunc, ok := ret.Get(0).(func(string, bool, bool) string); ok {
		r0 = returnFunc(version, force, quiet)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, bool, bool) error); ok {
		r1 = returnFunc(version, force, quiet)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockK0sctlManager_Download_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Download'
type MockK0sctlManager_Download_Call struct {
	*mock.Call
}

// Download is a helper method to define mock.On call
//   - version string
//   - force bool
//   - quiet bool
func (_e *MockK0sctlManager_Expecter) Download(version interface{}, force interface{}, quiet interface{}) *MockK0sctlManager_Download_Call {
	return &MockK0sctlManager_Download_Call{Call: _e.mock.On("Download", version, force, quiet)}
}

func (_c *MockK0sctlManager_Download_Call) Run(run func(version string, force bool, quiet bool)) *MockK0sctlManager_Download_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockK0sctlManager_Download_Call) Return(s string, err error) *MockK0sctlManager_Download_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockK0sctlManager_Download_Call) RunAndReturn(run func(version string, force bool, quiet bool) (string, error)) *MockK0sctlManager_Download_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestVersion provides a mock function for the type MockK0sctlManager
func (_mock *MockK0sctlManager) GetLatestVersion() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLatestVersion")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockK0sctlManager_GetLatestVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestVersion'
type MockK0sctlManager_GetLatestVersion_Call struct {
	*mock.Call
}

// GetLatestVersion is a helper method to define mock.On call
func (_e *MockK0sctlManager_Expecter) GetLatestVersion() *MockK0sctlManager_GetLatestVersion_Call {
	return &MockK0sctlManager_GetLatestVersion_Call{Call: _e.mock.On("GetLatestVersion")}
}

func (_c *MockK0sctlManager_GetLatestVersion_Call) Run(run func()) *MockK0sctlManager_GetLatestVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockK0sctlManager_GetLatestVersion_Call) Return(s string, err error) *MockK0sctlManager_GetLatestVersion_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockK0sctlManager_GetLatestVersion_Call) RunAndReturn(run func() (string, error)) *MockK0sctlManager_GetLatestVersion_Call {
	_c.Call.Return(run)
	return _c
}

// Reset provides a mock function for the type MockK0sctlManager
func (_mock *MockK0sctlManager) Reset(configPath string, k0sctlPath string) error {
	ret := _mock.Called(configPath, k0sctlPath)

	if len(ret) == 0 {
		panic("no return value specified for Reset")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(configPath, k0sctlPath)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockK0sctlManager_Reset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reset'
type MockK0sctlManager_Reset_Call struct {
	*mock.Call
}

// Reset is a helper method to define mock.On call
//   - configPath string
//   - k0sctlPath string
func (_e *MockK0sctlManager_Expecter) Reset(configPath interface{}, k0sctlPath interface{}) *MockK0sctlManager_Reset_Call {
	return &MockK0sctlManager_Reset_Call{Call: _e.mock.On("Reset", configPath, k0sctlPath)}
}

func (_c *MockK0sctlManager_Reset_Call) Run(run func(configPath string, k0sctlPath string)) *MockK0sctlManager_Reset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockK0sctlManager_Reset_Call) Return(err error) *MockK0sctlManager_Reset_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockK0sctlManager_Reset_Call) RunAndReturn(run func(configPath string, k0sctlPath string) error) *MockK0sctlManager_Reset_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPackageManager creates a new instance of MockPackageManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPackageManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPackageManager {
	mock := &MockPackageManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPackageManager is an autogenerated mock type for the PackageManager type
type MockPackageManager struct {
	mock.Mock
}

type MockPackageManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPackageManager) EXPECT() *MockPackageManager_Expecter {
	return &MockPackageManager_Expecter{mock: &_m.Mock}
}

// Extract provides a mock function for the type MockPackageManager
func (_mock *MockPackageManager) Extract(force bool) error {
	ret := _mock.Called(force)

	if len(ret) == 0 {
		panic("no return value specified for Extract")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(bool) error); ok {
		r0 = returnFunc(force)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPackageManager_Extract_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Extract'
type MockPackageManager_Extract_Call struct {
	*mock.Call
}

// Extract is a helper method to define mock.On call
//   - force bool
func (_e *MockPackageManager_Expecter) Extract(force interface{}) *MockPackageManager_Extract_Call {
	return &MockPackageManager_Extract_Call{Call: _e.mock.On("Extract", force)}
}

func (_c *MockPackageManager_Extract_Call) Run(run func(force bool)) *MockPackageManager_Extract_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPackageManager_Extract_Call) Return(err error) *MockPackageManager_Extract_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPackageManager_Extract_Call) RunAndReturn(run func(force bool) error) *MockPackageManager_Extract_Call {
	_c.Call.Return(run)
	return _c
}

// ExtractDependency provides a mock function for the type MockPackageManager
func (_mock *MockPackageManager) ExtractDependency(file string, force bool) error {
	ret := _mock.Called(file, force)

	if len(ret) == 0 {
		panic("no return value specified for ExtractDependency")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, bool) error); ok {
		r0 = returnFunc(file, force)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPackageManager_ExtractDependency_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExtractDependency'
type MockPackageManager_ExtractDependency_Call struct {
	*mock.Call
}

// ExtractDependency is a helper method to define mock.On call
//   - file string
//   - force bool
func (_e *MockPackageManager_Expecter) ExtractDependency(file interface{}, force interface{}) *MockPackageManager_ExtractDependency_Call {
	return &MockPackageManager_ExtractDependency_Call{Call: _e.mock.On("ExtractDependency", file, force)}
}

func (_c *MockPackageManager_ExtractDependency_Call) Run(run func(file string, force bool)) *MockPackageManager_ExtractDependency_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPackageManager_ExtractDependency_Call) Return(err error) *MockPackageManager_ExtractDependency_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPackageManager_ExtractDependency_Call) RunAndReturn(run func(file string, force bool) error) *MockPackageManager_ExtractDependency_Call {
	_c.Call.Return(run)
	return _c
}

// ExtractOciImageIndex provides a mock function for the type MockPackageManager
func (_mock *MockPackageManager) ExtractOciImageIndex(imagefile string) (files.OCIImageIndex, error) {
	ret := _mock.Called(imagefile)

	if len(ret) == 0 {
		panic("no return value specified for ExtractOciImageIndex")
	}

	var r0 files.OCIImageIndex
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (files.OCIImageIndex, error)); ok {
		return returnFunc(imagefile)
	}
	if returnFunc, ok := ret.Get(0).(func(string) files.OCIImageIndex); ok {
		r0 = returnFunc(imagefile)
	} else {
		r0 = ret.Get(0).(files.OCIImageIndex)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(imagefile)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPackageManager_ExtractOciImageIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExtractOciImageIndex'
type MockPackageManager_ExtractOciImageIndex_Call struct {
	*mock.Call
}

// ExtractOciImageIndex is a helper method to define mock.On call
//   - imagefile string
func (_e *MockPackageManager_Expecter) ExtractOciImageIndex(imagefile interface{}) *MockPackageManager_ExtractOciImageIndex_Call {
	return &MockPackageManager_ExtractOciImageIndex_Call{Call: _e.mock.On("ExtractOciImageIndex", imagefile)}
}

func (_c *MockPackageManager_ExtractOciImageIndex_Call) Run(run func(imagefile string)) *MockPackageManager_ExtractOciImageIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPackageManager_ExtractOciImageIndex_Call) Return(oCIImageIndex files.OCIImageIndex, err error) *MockPackageManager_ExtractOciImageIndex_Call {
	_c.Call.Return(oCIImageIndex, err)
	return _c
}

func (_c *MockPackageManager_ExtractOciImageIndex_Call) RunAndReturn(run func(imagefile string) (files.OCIImageIndex, error)) *MockPackageManager_ExtractOciImageIndex_Call {
	_c.Call.Return(run)
	return _c
}

// FileIO provides a mock function for the type MockPackageManager
func (_mock *MockPackageManager) FileIO() util.FileIO {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FileIO")
	}

	var r0 util.FileIO
	if returnFunc, ok := ret.Get(0).(func() util.FileIO); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(util.FileIO)
		}
	}
	return r0
}

// MockPackageManager_FileIO_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FileIO'
type MockPackageManager_FileIO_Call struct {
	*mock.Call
}

// FileIO is a helper method to define mock.On call
func (_e *MockPackageManager_Expecter) FileIO() *MockPackageManager_FileIO_Call {
	return &MockPackageManager_FileIO_Call{Call: _e.mock.On("FileIO")}
}

func (_c *MockPackageManager_FileIO_Call) Run(run func()) *MockPackageManager_FileIO_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPackageManager_FileIO_Call) Return(fileIO util.FileIO) *MockPackageManager_FileIO_Call {
	_c.Call.Return(fileIO)
	return _c
}

func (_c *MockPackageManager_FileIO_Call) RunAndReturn(run func() util.FileIO) *MockPackageManager_FileIO_Call {
	_c.Call.Return(run)
	return _c
}

// GetBaseimageName provides a mock function for the type MockPackageManager
func (_mock *MockPackageManager) GetBaseimageName(baseimage string) (string, error) {
	ret := _mock.Called(baseimage)

	if len(ret) == 0 {
		panic("no return value specified for GetBaseimageName")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(baseimage)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(baseimage)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(baseimage)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPackageManager_GetBaseimageName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBaseimageName'
type MockPackageManager_GetBaseimageName_Call struct {
	*mock.Call
}

// GetBaseimageName is a helper method to define mock.On call
//   - baseimage string
func (_e *MockPackageManager_Expecter) GetBaseimageName(baseimage interface{}) *MockPackageManager_GetBaseimageName_Call {
	return &MockPackageManager_GetBaseimageName_Call{Call: _e.mock.On("GetBaseimageName", baseimage)}
}

func (_c *MockPackageManager_GetBaseimageName_Call) Run(run func(baseimage string)) *MockPackageManager_GetBaseimageName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPackageManager_GetBaseimageName_Call) Return(s string, err error) *MockPackageManager_GetBaseimageName_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockPackageManager_GetBaseimageName_Call) RunAndReturn(run func(baseimage string) (string, error)) *MockPackageManager_GetBaseimageName_Call {
	_c.Call.Return(run)
	return _c
}

// GetBaseimagePath provides a mock function for the type MockPackageManager
func (_mock *MockPackageManager) GetBaseimagePath(baseimage string, force bool) (string, error) {
	ret := _mock.Called(baseimage, force)

	if len(ret) == 0 {
		panic("no return value specified for GetBaseimagePath")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, bool) (string, error)); ok {
		return returnFunc(baseimage, force)
	}
	if returnFunc, ok := ret.Get(0).(func(string, bool) string); ok {
		r0 = returnFunc(baseimage, force)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, bool) error); ok {
		r1 = returnFunc(baseimage, force)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPackageManager_GetBaseimagePath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBaseimagePath'
type MockPackageManager_GetBaseimagePath_Call struct {
	*mock.Call
}

// GetBaseimagePath is a helper method to define mock.On call
//   - baseimage string
//   - force bool
func (_e *MockPackageManager_Expecter) GetBaseimagePath(baseimage interface{}, force interface{}) *MockPackageManager_GetBaseimagePath_Call {
	return &MockPackageManager_GetBaseimagePath_Call{Call: _e.mock.On("GetBaseimagePath", baseimage, force)}
}

func (_c *MockPackageManager_GetBaseimagePath_Call) Run(run func(baseimage string, force bool)) *MockPackageManager_GetBaseimagePath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPackageManager_GetBaseimagePath_Call) Return(s string, err error) *MockPackageManager_GetBaseimagePath_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockPackageManager_GetBaseimagePath_Call) RunAndReturn(run func(baseimage string, force bool) (string, error)) *MockPackageManager_GetBaseimagePath_Call {
	_c.Call.Return(run)
	return _c
}

// GetCodesphereVersion provides a mock function for the type MockPackageManager
func (_mock *MockPackageManager) GetCodesphereVersion() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCodesphereVersion")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPackageManager_GetCodesphereVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCodesphereVersion'
type MockPackageManager_GetCodesphereVersion_Call struct {
	*mock.Call
}

// GetCodesphereVersion is a helper method to define mock.On call
func (_e *MockPackageManager_Expecter) GetCodesphereVersion() *MockPackageManager_GetCodesphereVersion_Call {
	return &MockPackageManager_GetCodesphereVersion_Call{Call: _e.mock.On("GetCodesphereVersion")}
}

func (_c *MockPackageManager_GetCodesphereVersion_Call) Run(run func()) *MockPackageManager_GetCodesphereVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPackageManager_GetCodesphereVersion_Call) Return(s string, err error) *MockPackageManager_GetCodesphereVersion_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockPackageManager_GetCodesphereVersion_Call) RunAndReturn(run func() (string, error)) *MockPackageManager_GetCodesphereVersion_Call {
	_c.Call.Return(run)
	return _c
}

// GetDependencyPath provides a mock function for the type MockPackageManager
func (_mock *MockPackageManager) GetDependencyPath(filename string) string {
	ret := _mock.Called(filename)

	if len(ret) == 0 {
		panic("no return value specified for GetDependencyPath")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(filename)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockPackageManager_GetDependencyPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDependencyPath'
type MockPackageManager_GetDependencyPath_Call struct {
	*mock.Call
}

// GetDependencyPath is a helper method to define mock.On call
//   - filename string
func (_e *MockPackageManager_Expecter) GetDependencyPath(filename interface{}) *MockPackageManager_GetDependencyPath_Call {
	return &MockPackageManager_GetDependencyPath_Call{Call: _e.mock.On("GetDependencyPath", filename)}
}

func (_c *MockPackageManager_GetDependencyPath_Call) Run(run func(filename string)) *MockPackageManager_GetDependencyPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPackageManager_GetDependencyPath_Call) Return(s string) *MockPackageManager_GetDependencyPath_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockPackageManager_GetDependencyPath_Call) RunAndReturn(run func(filename string) string) *MockPackageManager_GetDependencyPath_Call {
	_c.Call.Return(run)
	return _c
}

// GetWorkDir provides a mock function for the type MockPackageManager
func (_mock *MockPackageManager) GetWorkDir() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetWorkDir")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockPackageManager_GetWorkDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorkDir'
type MockPackageManager_GetWorkDir_Call struct {
	*mock.Call
}

// GetWorkDir is a helper method to define mock.On call
func (_e *MockPackageManager_Expecter) GetWorkDir() *MockPackageManager_GetWorkDir_Call {
	return &MockPackageManager_GetWorkDir_Call{Call: _e.mock.On("GetWorkDir")}
}

func (_c *MockPackageManager_GetWorkDir_Call) Run(run func()) *MockPackageManager_GetWorkDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPackageManager_GetWorkDir_Call) Return(s string) *MockPackageManager_GetWorkDir_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockPackageManager_GetWorkDir_Call) RunAndReturn(run func() string) *MockPackageManager_GetWorkDir_Call {
	_c.Call.Return(run)
	return _c
}
