// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package installer

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockK0sctlManager creates a new instance of MockK0sctlManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockK0sctlManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockK0sctlManager {
	mock := &MockK0sctlManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockK0sctlManager is an autogenerated mock type for the K0sctlManager type
type MockK0sctlManager struct {
	mock.Mock
}

type MockK0sctlManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockK0sctlManager) EXPECT() *MockK0sctlManager_Expecter {
	return &MockK0sctlManager_Expecter{mock: &_m.Mock}
}

// Apply provides a mock function for the type MockK0sctlManager
func (_mock *MockK0sctlManager) Apply(configPath string, k0sctlPath string, force bool) error {
	ret := _mock.Called(configPath, k0sctlPath, force)

	if len(ret) == 0 {
		panic("no return value specified for Apply")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, bool) error); ok {
		r0 = returnFunc(configPath, k0sctlPath, force)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockK0sctlManager_Apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Apply'
type MockK0sctlManager_Apply_Call struct {
	*mock.Call
}

// Apply is a helper method to define mock.On call
//   - configPath
//   - k0sctlPath
//   - force
func (_e *MockK0sctlManager_Expecter) Apply(configPath interface{}, k0sctlPath interface{}, force interface{}) *MockK0sctlManager_Apply_Call {
	return &MockK0sctlManager_Apply_Call{Call: _e.mock.On("Apply", configPath, k0sctlPath, force)}
}

func (_c *MockK0sctlManager_Apply_Call) Run(run func(configPath string, k0sctlPath string, force bool)) *MockK0sctlManager_Apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(bool))
	})
	return _c
}

func (_c *MockK0sctlManager_Apply_Call) Return(err error) *MockK0sctlManager_Apply_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockK0sctlManager_Apply_Call) RunAndReturn(run func(configPath string, k0sctlPath string, force bool) error) *MockK0sctlManager_Apply_Call {
	_c.Call.Return(run)
	return _c
}

// Download provides a mock function for the type MockK0sctlManager
func (_mock *MockK0sctlManager) Download(version string, force bool, quiet bool) (string, error) {
	ret := _mock.Called(version, force, quiet)

	if len(ret) == 0 {
		panic("no return value specified for Download")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, bool, bool) (string, error)); ok {
		return returnFunc(version, force, quiet)
	}
	if returnFunc, ok := ret.Get(0).(func(string, bool, bool) string); ok {
		r0 = returnFunc(version, force, quiet)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, bool, bool) error); ok {
		r1 = returnFunc(version, force, quiet)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockK0sctlManager_Download_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Download'
type MockK0sctlManager_Download_Call struct {
	*mock.Call
}

// Download is a helper method to define mock.On call
//   - version
//   - force
//   - quiet
func (_e *MockK0sctlManager_Expecter) Download(version interface{}, force interface{}, quiet interface{}) *MockK0sctlManager_Download_Call {
	return &MockK0sctlManager_Download_Call{Call: _e.mock.On("Download", version, force, quiet)}
}

func (_c *MockK0sctlManager_Download_Call) Run(run func(version string, force bool, quiet bool)) *MockK0sctlManager_Download_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(bool), args[2].(bool))
	})
	return _c
}

func (_c *MockK0sctlManager_Download_Call) Return(s string, err error) *MockK0sctlManager_Download_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockK0sctlManager_Download_Call) RunAndReturn(run func(version string, force bool, quiet bool) (string, error)) *MockK0sctlManager_Download_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestVersion provides a mock function for the type MockK0sctlManager
func (_mock *MockK0sctlManager) GetLatestVersion() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLatestVersion")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockK0sctlManager_GetLatestVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestVersion'
type MockK0sctlManager_GetLatestVersion_Call struct {
	*mock.Call
}

// GetLatestVersion is a helper method to define mock.On call
func (_e *MockK0sctlManager_Expecter) GetLatestVersion() *MockK0sctlManager_GetLatestVersion_Call {
	return &MockK0sctlManager_GetLatestVersion_Call{Call: _e.mock.On("GetLatestVersion")}
}

func (_c *MockK0sctlManager_GetLatestVersion_Call) Run(run func()) *MockK0sctlManager_GetLatestVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockK0sctlManager_GetLatestVersion_Call) Return(s string, err error) *MockK0sctlManager_GetLatestVersion_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockK0sctlManager_GetLatestVersion_Call) RunAndReturn(run func() (string, error)) *MockK0sctlManager_GetLatestVersion_Call {
	_c.Call.Return(run)
	return _c
}

// Reset provides a mock function for the type MockK0sctlManager
func (_mock *MockK0sctlManager) Reset(configPath string, k0sctlPath string) error {
	ret := _mock.Called(configPath, k0sctlPath)

	if len(ret) == 0 {
		panic("no return value specified for Reset")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(configPath, k0sctlPath)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockK0sctlManager_Reset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reset'
type MockK0sctlManager_Reset_Call struct {
	*mock.Call
}

// Reset is a helper method to define mock.On call
//   - configPath
//   - k0sctlPath
func (_e *MockK0sctlManager_Expecter) Reset(configPath interface{}, k0sctlPath interface{}) *MockK0sctlManager_Reset_Call {
	return &MockK0sctlManager_Reset_Call{Call: _e.mock.On("Reset", configPath, k0sctlPath)}
}

func (_c *MockK0sctlManager_Reset_Call) Run(run func(configPath string, k0sctlPath string)) *MockK0sctlManager_Reset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockK0sctlManager_Reset_Call) Return(err error) *MockK0sctlManager_Reset_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockK0sctlManager_Reset_Call) RunAndReturn(run func(configPath string, k0sctlPath string) error) *MockK0sctlManager_Reset_Call {
	_c.Call.Return(run)
	return _c
}
