// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package gcp

import (
	"cloud.google.com/go/artifactregistry/apiv1/artifactregistrypb"
	"cloud.google.com/go/compute/apiv1/computepb"
	"cloud.google.com/go/resourcemanager/apiv3/resourcemanagerpb"
	mock "github.com/stretchr/testify/mock"
	"google.golang.org/api/cloudbilling/v1"
	"google.golang.org/api/dns/v1"
)

// NewMockGCPClientManager creates a new instance of MockGCPClientManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGCPClientManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGCPClientManager {
	mock := &MockGCPClientManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGCPClientManager is an autogenerated mock type for the GCPClientManager type
type MockGCPClientManager struct {
	mock.Mock
}

type MockGCPClientManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGCPClientManager) EXPECT() *MockGCPClientManager_Expecter {
	return &MockGCPClientManager_Expecter{mock: &_m.Mock}
}

// AssignIAMRole provides a mock function for the type MockGCPClientManager
func (_mock *MockGCPClientManager) AssignIAMRole(projectID string, saEmail string, saProjectID string, roles []string) error {
	ret := _mock.Called(projectID, saEmail, saProjectID, roles)

	if len(ret) == 0 {
		panic("no return value specified for AssignIAMRole")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string, []string) error); ok {
		r0 = returnFunc(projectID, saEmail, saProjectID, roles)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGCPClientManager_AssignIAMRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignIAMRole'
type MockGCPClientManager_AssignIAMRole_Call struct {
	*mock.Call
}

// AssignIAMRole is a helper method to define mock.On call
//   - projectID
//   - saEmail
//   - saProjectID
//   - roles
func (_e *MockGCPClientManager_Expecter) AssignIAMRole(projectID interface{}, saEmail interface{}, saProjectID interface{}, roles interface{}) *MockGCPClientManager_AssignIAMRole_Call {
	return &MockGCPClientManager_AssignIAMRole_Call{Call: _e.mock.On("AssignIAMRole", projectID, saEmail, saProjectID, roles)}
}

func (_c *MockGCPClientManager_AssignIAMRole_Call) Run(run func(projectID string, saEmail string, saProjectID string, roles []string)) *MockGCPClientManager_AssignIAMRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string), args[3].([]string))
	})
	return _c
}

func (_c *MockGCPClientManager_AssignIAMRole_Call) Return(err error) *MockGCPClientManager_AssignIAMRole_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGCPClientManager_AssignIAMRole_Call) RunAndReturn(run func(projectID string, saEmail string, saProjectID string, roles []string) error) *MockGCPClientManager_AssignIAMRole_Call {
	_c.Call.Return(run)
	return _c
}

// CreateAddress provides a mock function for the type MockGCPClientManager
func (_mock *MockGCPClientManager) CreateAddress(projectID string, region string, address *computepb.Address) (string, error) {
	ret := _mock.Called(projectID, region, address)

	if len(ret) == 0 {
		panic("no return value specified for CreateAddress")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, *computepb.Address) (string, error)); ok {
		return returnFunc(projectID, region, address)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, *computepb.Address) string); ok {
		r0 = returnFunc(projectID, region, address)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, *computepb.Address) error); ok {
		r1 = returnFunc(projectID, region, address)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGCPClientManager_CreateAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAddress'
type MockGCPClientManager_CreateAddress_Call struct {
	*mock.Call
}

// CreateAddress is a helper method to define mock.On call
//   - projectID
//   - region
//   - address
func (_e *MockGCPClientManager_Expecter) CreateAddress(projectID interface{}, region interface{}, address interface{}) *MockGCPClientManager_CreateAddress_Call {
	return &MockGCPClientManager_CreateAddress_Call{Call: _e.mock.On("CreateAddress", projectID, region, address)}
}

func (_c *MockGCPClientManager_CreateAddress_Call) Run(run func(projectID string, region string, address *computepb.Address)) *MockGCPClientManager_CreateAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(*computepb.Address))
	})
	return _c
}

func (_c *MockGCPClientManager_CreateAddress_Call) Return(s string, err error) *MockGCPClientManager_CreateAddress_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockGCPClientManager_CreateAddress_Call) RunAndReturn(run func(projectID string, region string, address *computepb.Address) (string, error)) *MockGCPClientManager_CreateAddress_Call {
	_c.Call.Return(run)
	return _c
}

// CreateArtifactRegistry provides a mock function for the type MockGCPClientManager
func (_mock *MockGCPClientManager) CreateArtifactRegistry(projectID string, region string, repoName string) (*artifactregistrypb.Repository, error) {
	ret := _mock.Called(projectID, region, repoName)

	if len(ret) == 0 {
		panic("no return value specified for CreateArtifactRegistry")
	}

	var r0 *artifactregistrypb.Repository
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) (*artifactregistrypb.Repository, error)); ok {
		return returnFunc(projectID, region, repoName)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, string) *artifactregistrypb.Repository); ok {
		r0 = returnFunc(projectID, region, repoName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*artifactregistrypb.Repository)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = returnFunc(projectID, region, repoName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGCPClientManager_CreateArtifactRegistry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateArtifactRegistry'
type MockGCPClientManager_CreateArtifactRegistry_Call struct {
	*mock.Call
}

// CreateArtifactRegistry is a helper method to define mock.On call
//   - projectID
//   - region
//   - repoName
func (_e *MockGCPClientManager_Expecter) CreateArtifactRegistry(projectID interface{}, region interface{}, repoName interface{}) *MockGCPClientManager_CreateArtifactRegistry_Call {
	return &MockGCPClientManager_CreateArtifactRegistry_Call{Call: _e.mock.On("CreateArtifactRegistry", projectID, region, repoName)}
}

func (_c *MockGCPClientManager_CreateArtifactRegistry_Call) Run(run func(projectID string, region string, repoName string)) *MockGCPClientManager_CreateArtifactRegistry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockGCPClientManager_CreateArtifactRegistry_Call) Return(repository *artifactregistrypb.Repository, err error) *MockGCPClientManager_CreateArtifactRegistry_Call {
	_c.Call.Return(repository, err)
	return _c
}

func (_c *MockGCPClientManager_CreateArtifactRegistry_Call) RunAndReturn(run func(projectID string, region string, repoName string) (*artifactregistrypb.Repository, error)) *MockGCPClientManager_CreateArtifactRegistry_Call {
	_c.Call.Return(run)
	return _c
}

// CreateFirewallRule provides a mock function for the type MockGCPClientManager
func (_mock *MockGCPClientManager) CreateFirewallRule(projectID string, rule *computepb.Firewall) error {
	ret := _mock.Called(projectID, rule)

	if len(ret) == 0 {
		panic("no return value specified for CreateFirewallRule")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, *computepb.Firewall) error); ok {
		r0 = returnFunc(projectID, rule)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGCPClientManager_CreateFirewallRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateFirewallRule'
type MockGCPClientManager_CreateFirewallRule_Call struct {
	*mock.Call
}

// CreateFirewallRule is a helper method to define mock.On call
//   - projectID
//   - rule
func (_e *MockGCPClientManager_Expecter) CreateFirewallRule(projectID interface{}, rule interface{}) *MockGCPClientManager_CreateFirewallRule_Call {
	return &MockGCPClientManager_CreateFirewallRule_Call{Call: _e.mock.On("CreateFirewallRule", projectID, rule)}
}

func (_c *MockGCPClientManager_CreateFirewallRule_Call) Run(run func(projectID string, rule *computepb.Firewall)) *MockGCPClientManager_CreateFirewallRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*computepb.Firewall))
	})
	return _c
}

func (_c *MockGCPClientManager_CreateFirewallRule_Call) Return(err error) *MockGCPClientManager_CreateFirewallRule_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGCPClientManager_CreateFirewallRule_Call) RunAndReturn(run func(projectID string, rule *computepb.Firewall) error) *MockGCPClientManager_CreateFirewallRule_Call {
	_c.Call.Return(run)
	return _c
}

// CreateInstance provides a mock function for the type MockGCPClientManager
func (_mock *MockGCPClientManager) CreateInstance(projectID string, zone string, instance *computepb.Instance) error {
	ret := _mock.Called(projectID, zone, instance)

	if len(ret) == 0 {
		panic("no return value specified for CreateInstance")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, *computepb.Instance) error); ok {
		r0 = returnFunc(projectID, zone, instance)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGCPClientManager_CreateInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInstance'
type MockGCPClientManager_CreateInstance_Call struct {
	*mock.Call
}

// CreateInstance is a helper method to define mock.On call
//   - projectID
//   - zone
//   - instance
func (_e *MockGCPClientManager_Expecter) CreateInstance(projectID interface{}, zone interface{}, instance interface{}) *MockGCPClientManager_CreateInstance_Call {
	return &MockGCPClientManager_CreateInstance_Call{Call: _e.mock.On("CreateInstance", projectID, zone, instance)}
}

func (_c *MockGCPClientManager_CreateInstance_Call) Run(run func(projectID string, zone string, instance *computepb.Instance)) *MockGCPClientManager_CreateInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(*computepb.Instance))
	})
	return _c
}

func (_c *MockGCPClientManager_CreateInstance_Call) Return(err error) *MockGCPClientManager_CreateInstance_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGCPClientManager_CreateInstance_Call) RunAndReturn(run func(projectID string, zone string, instance *computepb.Instance) error) *MockGCPClientManager_CreateInstance_Call {
	_c.Call.Return(run)
	return _c
}

// CreateProject provides a mock function for the type MockGCPClientManager
func (_mock *MockGCPClientManager) CreateProject(parent string, projectName string, displayName string) (string, error) {
	ret := _mock.Called(parent, projectName, displayName)

	if len(ret) == 0 {
		panic("no return value specified for CreateProject")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) (string, error)); ok {
		return returnFunc(parent, projectName, displayName)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, string) string); ok {
		r0 = returnFunc(parent, projectName, displayName)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = returnFunc(parent, projectName, displayName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGCPClientManager_CreateProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProject'
type MockGCPClientManager_CreateProject_Call struct {
	*mock.Call
}

// CreateProject is a helper method to define mock.On call
//   - parent
//   - projectName
//   - displayName
func (_e *MockGCPClientManager_Expecter) CreateProject(parent interface{}, projectName interface{}, displayName interface{}) *MockGCPClientManager_CreateProject_Call {
	return &MockGCPClientManager_CreateProject_Call{Call: _e.mock.On("CreateProject", parent, projectName, displayName)}
}

func (_c *MockGCPClientManager_CreateProject_Call) Run(run func(parent string, projectName string, displayName string)) *MockGCPClientManager_CreateProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockGCPClientManager_CreateProject_Call) Return(s string, err error) *MockGCPClientManager_CreateProject_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockGCPClientManager_CreateProject_Call) RunAndReturn(run func(parent string, projectName string, displayName string) (string, error)) *MockGCPClientManager_CreateProject_Call {
	_c.Call.Return(run)
	return _c
}

// CreateProjectID provides a mock function for the type MockGCPClientManager
func (_mock *MockGCPClientManager) CreateProjectID(projectName string) string {
	ret := _mock.Called(projectName)

	if len(ret) == 0 {
		panic("no return value specified for CreateProjectID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(projectName)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockGCPClientManager_CreateProjectID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProjectID'
type MockGCPClientManager_CreateProjectID_Call struct {
	*mock.Call
}

// CreateProjectID is a helper method to define mock.On call
//   - projectName
func (_e *MockGCPClientManager_Expecter) CreateProjectID(projectName interface{}) *MockGCPClientManager_CreateProjectID_Call {
	return &MockGCPClientManager_CreateProjectID_Call{Call: _e.mock.On("CreateProjectID", projectName)}
}

func (_c *MockGCPClientManager_CreateProjectID_Call) Run(run func(projectName string)) *MockGCPClientManager_CreateProjectID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockGCPClientManager_CreateProjectID_Call) Return(s string) *MockGCPClientManager_CreateProjectID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockGCPClientManager_CreateProjectID_Call) RunAndReturn(run func(projectName string) string) *MockGCPClientManager_CreateProjectID_Call {
	_c.Call.Return(run)
	return _c
}

// CreateServiceAccount provides a mock function for the type MockGCPClientManager
func (_mock *MockGCPClientManager) CreateServiceAccount(projectID string, name string, displayName string) (string, bool, error) {
	ret := _mock.Called(projectID, name, displayName)

	if len(ret) == 0 {
		panic("no return value specified for CreateServiceAccount")
	}

	var r0 string
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) (string, bool, error)); ok {
		return returnFunc(projectID, name, displayName)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, string) string); ok {
		r0 = returnFunc(projectID, name, displayName)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, string) bool); ok {
		r1 = returnFunc(projectID, name, displayName)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(string, string, string) error); ok {
		r2 = returnFunc(projectID, name, displayName)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockGCPClientManager_CreateServiceAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateServiceAccount'
type MockGCPClientManager_CreateServiceAccount_Call struct {
	*mock.Call
}

// CreateServiceAccount is a helper method to define mock.On call
//   - projectID
//   - name
//   - displayName
func (_e *MockGCPClientManager_Expecter) CreateServiceAccount(projectID interface{}, name interface{}, displayName interface{}) *MockGCPClientManager_CreateServiceAccount_Call {
	return &MockGCPClientManager_CreateServiceAccount_Call{Call: _e.mock.On("CreateServiceAccount", projectID, name, displayName)}
}

func (_c *MockGCPClientManager_CreateServiceAccount_Call) Run(run func(projectID string, name string, displayName string)) *MockGCPClientManager_CreateServiceAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockGCPClientManager_CreateServiceAccount_Call) Return(s string, b bool, err error) *MockGCPClientManager_CreateServiceAccount_Call {
	_c.Call.Return(s, b, err)
	return _c
}

func (_c *MockGCPClientManager_CreateServiceAccount_Call) RunAndReturn(run func(projectID string, name string, displayName string) (string, bool, error)) *MockGCPClientManager_CreateServiceAccount_Call {
	_c.Call.Return(run)
	return _c
}

// CreateServiceAccountKey provides a mock function for the type MockGCPClientManager
func (_mock *MockGCPClientManager) CreateServiceAccountKey(projectID string, saEmail string) (string, error) {
	ret := _mock.Called(projectID, saEmail)

	if len(ret) == 0 {
		panic("no return value specified for CreateServiceAccountKey")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return returnFunc(projectID, saEmail)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = returnFunc(projectID, saEmail)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(projectID, saEmail)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGCPClientManager_CreateServiceAccountKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateServiceAccountKey'
type MockGCPClientManager_CreateServiceAccountKey_Call struct {
	*mock.Call
}

// CreateServiceAccountKey is a helper method to define mock.On call
//   - projectID
//   - saEmail
func (_e *MockGCPClientManager_Expecter) CreateServiceAccountKey(projectID interface{}, saEmail interface{}) *MockGCPClientManager_CreateServiceAccountKey_Call {
	return &MockGCPClientManager_CreateServiceAccountKey_Call{Call: _e.mock.On("CreateServiceAccountKey", projectID, saEmail)}
}

func (_c *MockGCPClientManager_CreateServiceAccountKey_Call) Run(run func(projectID string, saEmail string)) *MockGCPClientManager_CreateServiceAccountKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockGCPClientManager_CreateServiceAccountKey_Call) Return(s string, err error) *MockGCPClientManager_CreateServiceAccountKey_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockGCPClientManager_CreateServiceAccountKey_Call) RunAndReturn(run func(projectID string, saEmail string) (string, error)) *MockGCPClientManager_CreateServiceAccountKey_Call {
	_c.Call.Return(run)
	return _c
}

// CreateVPC provides a mock function for the type MockGCPClientManager
func (_mock *MockGCPClientManager) CreateVPC(projectID string, region string, networkName string, subnetName string, routerName string, natName string) error {
	ret := _mock.Called(projectID, region, networkName, subnetName, routerName, natName)

	if len(ret) == 0 {
		panic("no return value specified for CreateVPC")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string, string, string, string) error); ok {
		r0 = returnFunc(projectID, region, networkName, subnetName, routerName, natName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGCPClientManager_CreateVPC_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateVPC'
type MockGCPClientManager_CreateVPC_Call struct {
	*mock.Call
}

// CreateVPC is a helper method to define mock.On call
//   - projectID
//   - region
//   - networkName
//   - subnetName
//   - routerName
//   - natName
func (_e *MockGCPClientManager_Expecter) CreateVPC(projectID interface{}, region interface{}, networkName interface{}, subnetName interface{}, routerName interface{}, natName interface{}) *MockGCPClientManager_CreateVPC_Call {
	return &MockGCPClientManager_CreateVPC_Call{Call: _e.mock.On("CreateVPC", projectID, region, networkName, subnetName, routerName, natName)}
}

func (_c *MockGCPClientManager_CreateVPC_Call) Run(run func(projectID string, region string, networkName string, subnetName string, routerName string, natName string)) *MockGCPClientManager_CreateVPC_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string), args[3].(string), args[4].(string), args[5].(string))
	})
	return _c
}

func (_c *MockGCPClientManager_CreateVPC_Call) Return(err error) *MockGCPClientManager_CreateVPC_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGCPClientManager_CreateVPC_Call) RunAndReturn(run func(projectID string, region string, networkName string, subnetName string, routerName string, natName string) error) *MockGCPClientManager_CreateVPC_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteDNSRecordSets provides a mock function for the type MockGCPClientManager
func (_mock *MockGCPClientManager) DeleteDNSRecordSets(projectID string, zoneName string, baseDomain string) error {
	ret := _mock.Called(projectID, zoneName, baseDomain)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDNSRecordSets")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = returnFunc(projectID, zoneName, baseDomain)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGCPClientManager_DeleteDNSRecordSets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteDNSRecordSets'
type MockGCPClientManager_DeleteDNSRecordSets_Call struct {
	*mock.Call
}

// DeleteDNSRecordSets is a helper method to define mock.On call
//   - projectID
//   - zoneName
//   - baseDomain
func (_e *MockGCPClientManager_Expecter) DeleteDNSRecordSets(projectID interface{}, zoneName interface{}, baseDomain interface{}) *MockGCPClientManager_DeleteDNSRecordSets_Call {
	return &MockGCPClientManager_DeleteDNSRecordSets_Call{Call: _e.mock.On("DeleteDNSRecordSets", projectID, zoneName, baseDomain)}
}

func (_c *MockGCPClientManager_DeleteDNSRecordSets_Call) Run(run func(projectID string, zoneName string, baseDomain string)) *MockGCPClientManager_DeleteDNSRecordSets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockGCPClientManager_DeleteDNSRecordSets_Call) Return(err error) *MockGCPClientManager_DeleteDNSRecordSets_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGCPClientManager_DeleteDNSRecordSets_Call) RunAndReturn(run func(projectID string, zoneName string, baseDomain string) error) *MockGCPClientManager_DeleteDNSRecordSets_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteProject provides a mock function for the type MockGCPClientManager
func (_mock *MockGCPClientManager) DeleteProject(projectID string) error {
	ret := _mock.Called(projectID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProject")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(projectID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGCPClientManager_DeleteProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteProject'
type MockGCPClientManager_DeleteProject_Call struct {
	*mock.Call
}

// DeleteProject is a helper method to define mock.On call
//   - projectID
func (_e *MockGCPClientManager_Expecter) DeleteProject(projectID interface{}) *MockGCPClientManager_DeleteProject_Call {
	return &MockGCPClientManager_DeleteProject_Call{Call: _e.mock.On("DeleteProject", projectID)}
}

func (_c *MockGCPClientManager_DeleteProject_Call) Run(run func(projectID string)) *MockGCPClientManager_DeleteProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockGCPClientManager_DeleteProject_Call) Return(err error) *MockGCPClientManager_DeleteProject_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGCPClientManager_DeleteProject_Call) RunAndReturn(run func(projectID string) error) *MockGCPClientManager_DeleteProject_Call {
	_c.Call.Return(run)
	return _c
}

// EnableAPIs provides a mock function for the type MockGCPClientManager
func (_mock *MockGCPClientManager) EnableAPIs(projectID string, apis []string) error {
	ret := _mock.Called(projectID, apis)

	if len(ret) == 0 {
		panic("no return value specified for EnableAPIs")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []string) error); ok {
		r0 = returnFunc(projectID, apis)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGCPClientManager_EnableAPIs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnableAPIs'
type MockGCPClientManager_EnableAPIs_Call struct {
	*mock.Call
}

// EnableAPIs is a helper method to define mock.On call
//   - projectID
//   - apis
func (_e *MockGCPClientManager_Expecter) EnableAPIs(projectID interface{}, apis interface{}) *MockGCPClientManager_EnableAPIs_Call {
	return &MockGCPClientManager_EnableAPIs_Call{Call: _e.mock.On("EnableAPIs", projectID, apis)}
}

func (_c *MockGCPClientManager_EnableAPIs_Call) Run(run func(projectID string, apis []string)) *MockGCPClientManager_EnableAPIs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([]string))
	})
	return _c
}

func (_c *MockGCPClientManager_EnableAPIs_Call) Return(err error) *MockGCPClientManager_EnableAPIs_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGCPClientManager_EnableAPIs_Call) RunAndReturn(run func(projectID string, apis []string) error) *MockGCPClientManager_EnableAPIs_Call {
	_c.Call.Return(run)
	return _c
}

// EnableBilling provides a mock function for the type MockGCPClientManager
func (_mock *MockGCPClientManager) EnableBilling(projectID string, billingAccount string) error {
	ret := _mock.Called(projectID, billingAccount)

	if len(ret) == 0 {
		panic("no return value specified for EnableBilling")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(projectID, billingAccount)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGCPClientManager_EnableBilling_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnableBilling'
type MockGCPClientManager_EnableBilling_Call struct {
	*mock.Call
}

// EnableBilling is a helper method to define mock.On call
//   - projectID
//   - billingAccount
func (_e *MockGCPClientManager_Expecter) EnableBilling(projectID interface{}, billingAccount interface{}) *MockGCPClientManager_EnableBilling_Call {
	return &MockGCPClientManager_EnableBilling_Call{Call: _e.mock.On("EnableBilling", projectID, billingAccount)}
}

func (_c *MockGCPClientManager_EnableBilling_Call) Run(run func(projectID string, billingAccount string)) *MockGCPClientManager_EnableBilling_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockGCPClientManager_EnableBilling_Call) Return(err error) *MockGCPClientManager_EnableBilling_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGCPClientManager_EnableBilling_Call) RunAndReturn(run func(projectID string, billingAccount string) error) *MockGCPClientManager_EnableBilling_Call {
	_c.Call.Return(run)
	return _c
}

// EnsureDNSManagedZone provides a mock function for the type MockGCPClientManager
func (_mock *MockGCPClientManager) EnsureDNSManagedZone(projectID string, zoneName string, dnsName string, description string) error {
	ret := _mock.Called(projectID, zoneName, dnsName, description)

	if len(ret) == 0 {
		panic("no return value specified for EnsureDNSManagedZone")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string, string) error); ok {
		r0 = returnFunc(projectID, zoneName, dnsName, description)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGCPClientManager_EnsureDNSManagedZone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureDNSManagedZone'
type MockGCPClientManager_EnsureDNSManagedZone_Call struct {
	*mock.Call
}

// EnsureDNSManagedZone is a helper method to define mock.On call
//   - projectID
//   - zoneName
//   - dnsName
//   - description
func (_e *MockGCPClientManager_Expecter) EnsureDNSManagedZone(projectID interface{}, zoneName interface{}, dnsName interface{}, description interface{}) *MockGCPClientManager_EnsureDNSManagedZone_Call {
	return &MockGCPClientManager_EnsureDNSManagedZone_Call{Call: _e.mock.On("EnsureDNSManagedZone", projectID, zoneName, dnsName, description)}
}

func (_c *MockGCPClientManager_EnsureDNSManagedZone_Call) Run(run func(projectID string, zoneName string, dnsName string, description string)) *MockGCPClientManager_EnsureDNSManagedZone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockGCPClientManager_EnsureDNSManagedZone_Call) Return(err error) *MockGCPClientManager_EnsureDNSManagedZone_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGCPClientManager_EnsureDNSManagedZone_Call) RunAndReturn(run func(projectID string, zoneName string, dnsName string, description string) error) *MockGCPClientManager_EnsureDNSManagedZone_Call {
	_c.Call.Return(run)
	return _c
}

// EnsureDNSRecordSets provides a mock function for the type MockGCPClientManager
func (_mock *MockGCPClientManager) EnsureDNSRecordSets(projectID string, zoneName string, records []*dns.ResourceRecordSet) error {
	ret := _mock.Called(projectID, zoneName, records)

	if len(ret) == 0 {
		panic("no return value specified for EnsureDNSRecordSets")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, []*dns.ResourceRecordSet) error); ok {
		r0 = returnFunc(projectID, zoneName, records)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGCPClientManager_EnsureDNSRecordSets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureDNSRecordSets'
type MockGCPClientManager_EnsureDNSRecordSets_Call struct {
	*mock.Call
}

// EnsureDNSRecordSets is a helper method to define mock.On call
//   - projectID
//   - zoneName
//   - records
func (_e *MockGCPClientManager_Expecter) EnsureDNSRecordSets(projectID interface{}, zoneName interface{}, records interface{}) *MockGCPClientManager_EnsureDNSRecordSets_Call {
	return &MockGCPClientManager_EnsureDNSRecordSets_Call{Call: _e.mock.On("EnsureDNSRecordSets", projectID, zoneName, records)}
}

func (_c *MockGCPClientManager_EnsureDNSRecordSets_Call) Run(run func(projectID string, zoneName string, records []*dns.ResourceRecordSet)) *MockGCPClientManager_EnsureDNSRecordSets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].([]*dns.ResourceRecordSet))
	})
	return _c
}

func (_c *MockGCPClientManager_EnsureDNSRecordSets_Call) Return(err error) *MockGCPClientManager_EnsureDNSRecordSets_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGCPClientManager_EnsureDNSRecordSets_Call) RunAndReturn(run func(projectID string, zoneName string, records []*dns.ResourceRecordSet) error) *MockGCPClientManager_EnsureDNSRecordSets_Call {
	_c.Call.Return(run)
	return _c
}

// GetAddress provides a mock function for the type MockGCPClientManager
func (_mock *MockGCPClientManager) GetAddress(projectID string, region string, addressName string) (*computepb.Address, error) {
	ret := _mock.Called(projectID, region, addressName)

	if len(ret) == 0 {
		panic("no return value specified for GetAddress")
	}

	var r0 *computepb.Address
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) (*computepb.Address, error)); ok {
		return returnFunc(projectID, region, addressName)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, string) *computepb.Address); ok {
		r0 = returnFunc(projectID, region, addressName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*computepb.Address)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = returnFunc(projectID, region, addressName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGCPClientManager_GetAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAddress'
type MockGCPClientManager_GetAddress_Call struct {
	*mock.Call
}

// GetAddress is a helper method to define mock.On call
//   - projectID
//   - region
//   - addressName
func (_e *MockGCPClientManager_Expecter) GetAddress(projectID interface{}, region interface{}, addressName interface{}) *MockGCPClientManager_GetAddress_Call {
	return &MockGCPClientManager_GetAddress_Call{Call: _e.mock.On("GetAddress", projectID, region, addressName)}
}

func (_c *MockGCPClientManager_GetAddress_Call) Run(run func(projectID string, region string, addressName string)) *MockGCPClientManager_GetAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockGCPClientManager_GetAddress_Call) Return(address *computepb.Address, err error) *MockGCPClientManager_GetAddress_Call {
	_c.Call.Return(address, err)
	return _c
}

func (_c *MockGCPClientManager_GetAddress_Call) RunAndReturn(run func(projectID string, region string, addressName string) (*computepb.Address, error)) *MockGCPClientManager_GetAddress_Call {
	_c.Call.Return(run)
	return _c
}

// GetArtifactRegistry provides a mock function for the type MockGCPClientManager
func (_mock *MockGCPClientManager) GetArtifactRegistry(projectID string, region string, repoName string) (*artifactregistrypb.Repository, error) {
	ret := _mock.Called(projectID, region, repoName)

	if len(ret) == 0 {
		panic("no return value specified for GetArtifactRegistry")
	}

	var r0 *artifactregistrypb.Repository
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) (*artifactregistrypb.Repository, error)); ok {
		return returnFunc(projectID, region, repoName)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, string) *artifactregistrypb.Repository); ok {
		r0 = returnFunc(projectID, region, repoName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*artifactregistrypb.Repository)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = returnFunc(projectID, region, repoName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGCPClientManager_GetArtifactRegistry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetArtifactRegistry'
type MockGCPClientManager_GetArtifactRegistry_Call struct {
	*mock.Call
}

// GetArtifactRegistry is a helper method to define mock.On call
//   - projectID
//   - region
//   - repoName
func (_e *MockGCPClientManager_Expecter) GetArtifactRegistry(projectID interface{}, region interface{}, repoName interface{}) *MockGCPClientManager_GetArtifactRegistry_Call {
	return &MockGCPClientManager_GetArtifactRegistry_Call{Call: _e.mock.On("GetArtifactRegistry", projectID, region, repoName)}
}

func (_c *MockGCPClientManager_GetArtifactRegistry_Call) Run(run func(projectID string, region string, repoName string)) *MockGCPClientManager_GetArtifactRegistry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockGCPClientManager_GetArtifactRegistry_Call) Return(repository *artifactregistrypb.Repository, err error) *MockGCPClientManager_GetArtifactRegistry_Call {
	_c.Call.Return(repository, err)
	return _c
}

func (_c *MockGCPClientManager_GetArtifactRegistry_Call) RunAndReturn(run func(projectID string, region string, repoName string) (*artifactregistrypb.Repository, error)) *MockGCPClientManager_GetArtifactRegistry_Call {
	_c.Call.Return(run)
	return _c
}

// GetBillingInfo provides a mock function for the type MockGCPClientManager
func (_mock *MockGCPClientManager) GetBillingInfo(projectID string) (*cloudbilling.ProjectBillingInfo, error) {
	ret := _mock.Called(projectID)

	if len(ret) == 0 {
		panic("no return value specified for GetBillingInfo")
	}

	var r0 *cloudbilling.ProjectBillingInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*cloudbilling.ProjectBillingInfo, error)); ok {
		return returnFunc(projectID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *cloudbilling.ProjectBillingInfo); ok {
		r0 = returnFunc(projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudbilling.ProjectBillingInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(projectID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGCPClientManager_GetBillingInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBillingInfo'
type MockGCPClientManager_GetBillingInfo_Call struct {
	*mock.Call
}

// GetBillingInfo is a helper method to define mock.On call
//   - projectID
func (_e *MockGCPClientManager_Expecter) GetBillingInfo(projectID interface{}) *MockGCPClientManager_GetBillingInfo_Call {
	return &MockGCPClientManager_GetBillingInfo_Call{Call: _e.mock.On("GetBillingInfo", projectID)}
}

func (_c *MockGCPClientManager_GetBillingInfo_Call) Run(run func(projectID string)) *MockGCPClientManager_GetBillingInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockGCPClientManager_GetBillingInfo_Call) Return(projectBillingInfo *cloudbilling.ProjectBillingInfo, err error) *MockGCPClientManager_GetBillingInfo_Call {
	_c.Call.Return(projectBillingInfo, err)
	return _c
}

func (_c *MockGCPClientManager_GetBillingInfo_Call) RunAndReturn(run func(projectID string) (*cloudbilling.ProjectBillingInfo, error)) *MockGCPClientManager_GetBillingInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetInstance provides a mock function for the type MockGCPClientManager
func (_mock *MockGCPClientManager) GetInstance(projectID string, zone string, instanceName string) (*computepb.Instance, error) {
	ret := _mock.Called(projectID, zone, instanceName)

	if len(ret) == 0 {
		panic("no return value specified for GetInstance")
	}

	var r0 *computepb.Instance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) (*computepb.Instance, error)); ok {
		return returnFunc(projectID, zone, instanceName)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, string) *computepb.Instance); ok {
		r0 = returnFunc(projectID, zone, instanceName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*computepb.Instance)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = returnFunc(projectID, zone, instanceName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGCPClientManager_GetInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInstance'
type MockGCPClientManager_GetInstance_Call struct {
	*mock.Call
}

// GetInstance is a helper method to define mock.On call
//   - projectID
//   - zone
//   - instanceName
func (_e *MockGCPClientManager_Expecter) GetInstance(projectID interface{}, zone interface{}, instanceName interface{}) *MockGCPClientManager_GetInstance_Call {
	return &MockGCPClientManager_GetInstance_Call{Call: _e.mock.On("GetInstance", projectID, zone, instanceName)}
}

func (_c *MockGCPClientManager_GetInstance_Call) Run(run func(projectID string, zone string, instanceName string)) *MockGCPClientManager_GetInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockGCPClientManager_GetInstance_Call) Return(instance *computepb.Instance, err error) *MockGCPClientManager_GetInstance_Call {
	_c.Call.Return(instance, err)
	return _c
}

func (_c *MockGCPClientManager_GetInstance_Call) RunAndReturn(run func(projectID string, zone string, instanceName string) (*computepb.Instance, error)) *MockGCPClientManager_GetInstance_Call {
	_c.Call.Return(run)
	return _c
}

// GetProjectByName provides a mock function for the type MockGCPClientManager
func (_mock *MockGCPClientManager) GetProjectByName(folderID string, displayName string) (*resourcemanagerpb.Project, error) {
	ret := _mock.Called(folderID, displayName)

	if len(ret) == 0 {
		panic("no return value specified for GetProjectByName")
	}

	var r0 *resourcemanagerpb.Project
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (*resourcemanagerpb.Project, error)); ok {
		return returnFunc(folderID, displayName)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) *resourcemanagerpb.Project); ok {
		r0 = returnFunc(folderID, displayName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*resourcemanagerpb.Project)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(folderID, displayName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGCPClientManager_GetProjectByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProjectByName'
type MockGCPClientManager_GetProjectByName_Call struct {
	*mock.Call
}

// GetProjectByName is a helper method to define mock.On call
//   - folderID
//   - displayName
func (_e *MockGCPClientManager_Expecter) GetProjectByName(folderID interface{}, displayName interface{}) *MockGCPClientManager_GetProjectByName_Call {
	return &MockGCPClientManager_GetProjectByName_Call{Call: _e.mock.On("GetProjectByName", folderID, displayName)}
}

func (_c *MockGCPClientManager_GetProjectByName_Call) Run(run func(folderID string, displayName string)) *MockGCPClientManager_GetProjectByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockGCPClientManager_GetProjectByName_Call) Return(project *resourcemanagerpb.Project, err error) *MockGCPClientManager_GetProjectByName_Call {
	_c.Call.Return(project, err)
	return _c
}

func (_c *MockGCPClientManager_GetProjectByName_Call) RunAndReturn(run func(folderID string, displayName string) (*resourcemanagerpb.Project, error)) *MockGCPClientManager_GetProjectByName_Call {
	_c.Call.Return(run)
	return _c
}

// GrantImpersonation provides a mock function for the type MockGCPClientManager
func (_mock *MockGCPClientManager) GrantImpersonation(impersonatingServiceAccount string, impersonatingProjectID string, impersonatedServiceAccount string, impersonatedProjectID string) error {
	ret := _mock.Called(impersonatingServiceAccount, impersonatingProjectID, impersonatedServiceAccount, impersonatedProjectID)

	if len(ret) == 0 {
		panic("no return value specified for GrantImpersonation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string, string) error); ok {
		r0 = returnFunc(impersonatingServiceAccount, impersonatingProjectID, impersonatedServiceAccount, impersonatedProjectID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGCPClientManager_GrantImpersonation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GrantImpersonation'
type MockGCPClientManager_GrantImpersonation_Call struct {
	*mock.Call
}

// GrantImpersonation is a helper method to define mock.On call
//   - impersonatingServiceAccount
//   - impersonatingProjectID
//   - impersonatedServiceAccount
//   - impersonatedProjectID
func (_e *MockGCPClientManager_Expecter) GrantImpersonation(impersonatingServiceAccount interface{}, impersonatingProjectID interface{}, impersonatedServiceAccount interface{}, impersonatedProjectID interface{}) *MockGCPClientManager_GrantImpersonation_Call {
	return &MockGCPClientManager_GrantImpersonation_Call{Call: _e.mock.On("GrantImpersonation", impersonatingServiceAccount, impersonatingProjectID, impersonatedServiceAccount, impersonatedProjectID)}
}

func (_c *MockGCPClientManager_GrantImpersonation_Call) Run(run func(impersonatingServiceAccount string, impersonatingProjectID string, impersonatedServiceAccount string, impersonatedProjectID string)) *MockGCPClientManager_GrantImpersonation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockGCPClientManager_GrantImpersonation_Call) Return(err error) *MockGCPClientManager_GrantImpersonation_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGCPClientManager_GrantImpersonation_Call) RunAndReturn(run func(impersonatingServiceAccount string, impersonatingProjectID string, impersonatedServiceAccount string, impersonatedProjectID string) error) *MockGCPClientManager_GrantImpersonation_Call {
	_c.Call.Return(run)
	return _c
}

// IsOMSManagedProject provides a mock function for the type MockGCPClientManager
func (_mock *MockGCPClientManager) IsOMSManagedProject(projectID string) (bool, error) {
	ret := _mock.Called(projectID)

	if len(ret) == 0 {
		panic("no return value specified for IsOMSManagedProject")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return returnFunc(projectID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(projectID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(projectID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGCPClientManager_IsOMSManagedProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsOMSManagedProject'
type MockGCPClientManager_IsOMSManagedProject_Call struct {
	*mock.Call
}

// IsOMSManagedProject is a helper method to define mock.On call
//   - projectID
func (_e *MockGCPClientManager_Expecter) IsOMSManagedProject(projectID interface{}) *MockGCPClientManager_IsOMSManagedProject_Call {
	return &MockGCPClientManager_IsOMSManagedProject_Call{Call: _e.mock.On("IsOMSManagedProject", projectID)}
}

func (_c *MockGCPClientManager_IsOMSManagedProject_Call) Run(run func(projectID string)) *MockGCPClientManager_IsOMSManagedProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockGCPClientManager_IsOMSManagedProject_Call) Return(b bool, err error) *MockGCPClientManager_IsOMSManagedProject_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockGCPClientManager_IsOMSManagedProject_Call) RunAndReturn(run func(projectID string) (bool, error)) *MockGCPClientManager_IsOMSManagedProject_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeImpersonation provides a mock function for the type MockGCPClientManager
func (_mock *MockGCPClientManager) RevokeImpersonation(impersonatingServiceAccount string, impersonatingProjectID string, impersonatedServiceAccount string, impersonatedProjectID string) error {
	ret := _mock.Called(impersonatingServiceAccount, impersonatingProjectID, impersonatedServiceAccount, impersonatedProjectID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeImpersonation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string, string) error); ok {
		r0 = returnFunc(impersonatingServiceAccount, impersonatingProjectID, impersonatedServiceAccount, impersonatedProjectID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGCPClientManager_RevokeImpersonation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeImpersonation'
type MockGCPClientManager_RevokeImpersonation_Call struct {
	*mock.Call
}

// RevokeImpersonation is a helper method to define mock.On call
//   - impersonatingServiceAccount
//   - impersonatingProjectID
//   - impersonatedServiceAccount
//   - impersonatedProjectID
func (_e *MockGCPClientManager_Expecter) RevokeImpersonation(impersonatingServiceAccount interface{}, impersonatingProjectID interface{}, impersonatedServiceAccount interface{}, impersonatedProjectID interface{}) *MockGCPClientManager_RevokeImpersonation_Call {
	return &MockGCPClientManager_RevokeImpersonation_Call{Call: _e.mock.On("RevokeImpersonation", impersonatingServiceAccount, impersonatingProjectID, impersonatedServiceAccount, impersonatedProjectID)}
}

func (_c *MockGCPClientManager_RevokeImpersonation_Call) Run(run func(impersonatingServiceAccount string, impersonatingProjectID string, impersonatedServiceAccount string, impersonatedProjectID string)) *MockGCPClientManager_RevokeImpersonation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockGCPClientManager_RevokeImpersonation_Call) Return(err error) *MockGCPClientManager_RevokeImpersonation_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGCPClientManager_RevokeImpersonation_Call) RunAndReturn(run func(impersonatingServiceAccount string, impersonatingProjectID string, impersonatedServiceAccount string, impersonatedProjectID string) error) *MockGCPClientManager_RevokeImpersonation_Call {
	_c.Call.Return(run)
	return _c
}
