// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package prompt

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockPrompter creates a new instance of MockPrompter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPrompter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPrompter {
	mock := &MockPrompter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPrompter is an autogenerated mock type for the Prompter type
type MockPrompter struct {
	mock.Mock
}

type MockPrompter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPrompter) EXPECT() *MockPrompter_Expecter {
	return &MockPrompter_Expecter{mock: &_m.Mock}
}

// Bool provides a mock function for the type MockPrompter
func (_mock *MockPrompter) Bool(prompt string, defaultValue bool) bool {
	ret := _mock.Called(prompt, defaultValue)

	if len(ret) == 0 {
		panic("no return value specified for Bool")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string, bool) bool); ok {
		r0 = returnFunc(prompt, defaultValue)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockPrompter_Bool_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Bool'
type MockPrompter_Bool_Call struct {
	*mock.Call
}

// Bool is a helper method to define mock.On call
//   - prompt string
//   - defaultValue bool
func (_e *MockPrompter_Expecter) Bool(prompt any, defaultValue any) *MockPrompter_Bool_Call {
	return &MockPrompter_Bool_Call{Call: _e.mock.On("Bool", prompt, defaultValue)}
}

func (_c *MockPrompter_Bool_Call) Run(run func(prompt string, defaultValue bool)) *MockPrompter_Bool_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPrompter_Bool_Call) Return(b bool) *MockPrompter_Bool_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockPrompter_Bool_Call) RunAndReturn(run func(prompt string, defaultValue bool) bool) *MockPrompter_Bool_Call {
	_c.Call.Return(run)
	return _c
}

// Choice provides a mock function for the type MockPrompter
func (_mock *MockPrompter) Choice(prompt string, choices []string, defaultValue string) string {
	ret := _mock.Called(prompt, choices, defaultValue)

	if len(ret) == 0 {
		panic("no return value specified for Choice")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string, []string, string) string); ok {
		r0 = returnFunc(prompt, choices, defaultValue)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockPrompter_Choice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Choice'
type MockPrompter_Choice_Call struct {
	*mock.Call
}

// Choice is a helper method to define mock.On call
//   - prompt string
//   - choices []string
//   - defaultValue string
func (_e *MockPrompter_Expecter) Choice(prompt any, choices any, defaultValue any) *MockPrompter_Choice_Call {
	return &MockPrompter_Choice_Call{Call: _e.mock.On("Choice", prompt, choices, defaultValue)}
}

func (_c *MockPrompter_Choice_Call) Run(run func(prompt string, choices []string, defaultValue string)) *MockPrompter_Choice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPrompter_Choice_Call) Return(s string) *MockPrompter_Choice_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockPrompter_Choice_Call) RunAndReturn(run func(prompt string, choices []string, defaultValue string) string) *MockPrompter_Choice_Call {
	_c.Call.Return(run)
	return _c
}

// Int provides a mock function for the type MockPrompter
func (_mock *MockPrompter) Int(prompt string, defaultValue int) int {
	ret := _mock.Called(prompt, defaultValue)

	if len(ret) == 0 {
		panic("no return value specified for Int")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func(string, int) int); ok {
		r0 = returnFunc(prompt, defaultValue)
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockPrompter_Int_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Int'
type MockPrompter_Int_Call struct {
	*mock.Call
}

// Int is a helper method to define mock.On call
//   - prompt string
//   - defaultValue int
func (_e *MockPrompter_Expecter) Int(prompt any, defaultValue any) *MockPrompter_Int_Call {
	return &MockPrompter_Int_Call{Call: _e.mock.On("Int", prompt, defaultValue)}
}

func (_c *MockPrompter_Int_Call) Run(run func(prompt string, defaultValue int)) *MockPrompter_Int_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPrompter_Int_Call) Return(n int) *MockPrompter_Int_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockPrompter_Int_Call) RunAndReturn(run func(prompt string, defaultValue int) int) *MockPrompter_Int_Call {
	_c.Call.Return(run)
	return _c
}

// String provides a mock function for the type MockPrompter
func (_mock *MockPrompter) String(prompt string, defaultValue string) string {
	ret := _mock.Called(prompt, defaultValue)

	if len(ret) == 0 {
		panic("no return value specified for String")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = returnFunc(prompt, defaultValue)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockPrompter_String_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'String'
type MockPrompter_String_Call struct {
	*mock.Call
}

// String is a helper method to define mock.On call
//   - prompt string
//   - defaultValue string
func (_e *MockPrompter_Expecter) String(prompt any, defaultValue any) *MockPrompter_String_Call {
	return &MockPrompter_String_Call{Call: _e.mock.On("String", prompt, defaultValue)}
}

func (_c *MockPrompter_String_Call) Run(run func(prompt string, defaultValue string)) *MockPrompter_String_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPrompter_String_Call) Return(s string) *MockPrompter_String_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockPrompter_String_Call) RunAndReturn(run func(prompt string, defaultValue string) string) *MockPrompter_String_Call {
	_c.Call.Return(run)
	return _c
}

// StringSlice provides a mock function for the type MockPrompter
func (_mock *MockPrompter) StringSlice(prompt string, defaultValue []string) []string {
	ret := _mock.Called(prompt, defaultValue)

	if len(ret) == 0 {
		panic("no return value specified for StringSlice")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func(string, []string) []string); ok {
		r0 = returnFunc(prompt, defaultValue)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockPrompter_StringSlice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StringSlice'
type MockPrompter_StringSlice_Call struct {
	*mock.Call
}

// StringSlice is a helper method to define mock.On call
//   - prompt string
//   - defaultValue []string
func (_e *MockPrompter_Expecter) StringSlice(prompt any, defaultValue any) *MockPrompter_StringSlice_Call {
	return &MockPrompter_StringSlice_Call{Call: _e.mock.On("StringSlice", prompt, defaultValue)}
}

func (_c *MockPrompter_StringSlice_Call) Run(run func(prompt string, defaultValue []string)) *MockPrompter_StringSlice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPrompter_StringSlice_Call) Return(strings []string) *MockPrompter_StringSlice_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockPrompter_StringSlice_Call) RunAndReturn(run func(prompt string, defaultValue []string) []string) *MockPrompter_StringSlice_Call {
	_c.Call.Return(run)
	return _c
}
