// Copyright (c) Codesphere Inc.
// SPDX-License-Identifier: Apache-2.0

// Package filebackend contains implementation details shared by file-backed vaults.
package filebackend

import (
	"fmt"
	"path/filepath"

	"github.com/codesphere-cloud/oms/internal/installer/files"
	"github.com/codesphere-cloud/oms/internal/util"
	"go.yaml.in/yaml/v3"
)

// Options contains configuration shared by file-backed vault implementations.
type Options struct {
	Path         string
	WithComments bool
	FileIO       util.FileIO
}

// WithDefaults fills optional file backend dependencies.
func WithDefaults(opts Options) Options {
	if opts.FileIO == nil {
		opts.FileIO = util.NewFilesystemWriter()
	}

	return opts
}

// Marshal serializes install vault data for storage.
func Marshal(data *files.InstallVault, comments bool) ([]byte, error) {
	if data == nil {
		data = &files.InstallVault{}
	}

	plain, err := data.Marshal()
	if err != nil {
		return nil, fmt.Errorf("failed to marshal vault: %w", err)
	}

	if comments {
		plain = append([]byte("# Codesphere Installer Secrets\n# Generated by OMS CLI\n\n"), plain...)
	}

	return plain, nil
}

// Write atomically writes vault data to path.
func Write(fileIO util.FileIO, path string, data []byte) error {
	if err := fileIO.MkdirAll(filepath.Dir(path), 0700); err != nil {
		return fmt.Errorf("failed to create vault directory: %w", err)
	}

	tmpPath, err := fileIO.CreateTemp(filepath.Dir(path), ".vault-*")
	if err != nil {
		return fmt.Errorf("failed to create temporary vault: %w", err)
	}
	defer func() { _ = fileIO.Remove(tmpPath) }()

	if err := fileIO.WriteFile(tmpPath, data, 0600); err != nil {
		return fmt.Errorf("failed to write vault: %w", err)
	}

	if err := fileIO.Rename(tmpPath, path); err != nil {
		return fmt.Errorf("failed to replace vault: %w", err)
	}

	return nil
}

// IsSOPSEncryptedYAML reports whether a YAML document contains SOPS metadata.
func IsSOPSEncryptedYAML(data []byte) (bool, error) {
	var doc yaml.Node
	if err := yaml.Unmarshal(data, &doc); err != nil {
		return false, fmt.Errorf("failed to inspect YAML for SOPS metadata: %w", err)
	}

	if len(doc.Content) == 0 {
		return false, nil
	}

	root := doc.Content[0]
	if root.Kind != yaml.MappingNode {
		return false, nil
	}

	for i := 0; i+1 < len(root.Content); i += 2 {
		if root.Content[i].Value == "sops" && root.Content[i+1].Kind == yaml.MappingNode {
			return true, nil
		}
	}

	return false, nil
}

// Parse unmarshals vault YAML, including SOPS whole-file wrapper output.
func Parse(data []byte) (*files.InstallVault, error) {
	data = unwrapSOPSData(data)

	vault := &files.InstallVault{}
	if err := vault.Unmarshal(data); err != nil {
		return nil, fmt.Errorf("failed to unmarshal vault data: %w", err)
	}

	return vault, nil
}

// unwrapSOPSData strips a top-level data literal-block wrapper when present.
func unwrapSOPSData(data []byte) []byte {
	var doc yaml.Node
	if err := yaml.Unmarshal(data, &doc); err != nil || len(doc.Content) == 0 {
		return data
	}

	root := doc.Content[0]
	if root.Kind != yaml.MappingNode || len(root.Content) != 2 {
		return data
	}

	keyNode := root.Content[0]

	valueNode := root.Content[1]
	if keyNode.Value != "data" || valueNode.Kind != yaml.ScalarNode {
		return data
	}

	return []byte(valueNode.Value)
}
