// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package argocd

import (
	"context"
	mock "github.com/stretchr/testify/mock"
)

// NewMockArgoCDResources creates a new instance of MockArgoCDResources. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockArgoCDResources(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockArgoCDResources {
	mock := &MockArgoCDResources{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockArgoCDResources is an autogenerated mock type for the ArgoCDResources type
type MockArgoCDResources struct {
	mock.Mock
}

type MockArgoCDResources_Expecter struct {
	mock *mock.Mock
}

func (_m *MockArgoCDResources) EXPECT() *MockArgoCDResources_Expecter {
	return &MockArgoCDResources_Expecter{mock: &_m.Mock}
}

// ApplyAll provides a mock function for the type MockArgoCDResources
func (_mock *MockArgoCDResources) ApplyAll(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ApplyAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockArgoCDResources_ApplyAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyAll'
type MockArgoCDResources_ApplyAll_Call struct {
	*mock.Call
}

// ApplyAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockArgoCDResources_Expecter) ApplyAll(ctx any) *MockArgoCDResources_ApplyAll_Call {
	return &MockArgoCDResources_ApplyAll_Call{Call: _e.mock.On("ApplyAll", ctx)}
}

func (_c *MockArgoCDResources_ApplyAll_Call) Run(run func(ctx context.Context)) *MockArgoCDResources_ApplyAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockArgoCDResources_ApplyAll_Call) Return(err error) *MockArgoCDResources_ApplyAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockArgoCDResources_ApplyAll_Call) RunAndReturn(run func(ctx context.Context) error) *MockArgoCDResources_ApplyAll_Call {
	_c.Call.Return(run)
	return _c
}
