// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package cmd

import (
	"context"
	"github.com/creativeprojects/go-selfupdate"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOMSUpdater creates a new instance of MockOMSUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOMSUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOMSUpdater {
	mock := &MockOMSUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOMSUpdater is an autogenerated mock type for the OMSUpdater type
type MockOMSUpdater struct {
	mock.Mock
}

type MockOMSUpdater_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOMSUpdater) EXPECT() *MockOMSUpdater_Expecter {
	return &MockOMSUpdater_Expecter{mock: &_m.Mock}
}

// Update provides a mock function for the type MockOMSUpdater
func (_mock *MockOMSUpdater) Update(ctx context.Context, current string, repo selfupdate.Repository) (string, string, error) {
	ret := _mock.Called(ctx, current, repo)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 string
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, selfupdate.Repository) (string, string, error)); ok {
		return returnFunc(ctx, current, repo)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, selfupdate.Repository) string); ok {
		r0 = returnFunc(ctx, current, repo)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, selfupdate.Repository) string); ok {
		r1 = returnFunc(ctx, current, repo)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, selfupdate.Repository) error); ok {
		r2 = returnFunc(ctx, current, repo)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockOMSUpdater_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockOMSUpdater_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - current string
//   - repo selfupdate.Repository
func (_e *MockOMSUpdater_Expecter) Update(ctx interface{}, current interface{}, repo interface{}) *MockOMSUpdater_Update_Call {
	return &MockOMSUpdater_Update_Call{Call: _e.mock.On("Update", ctx, current, repo)}
}

func (_c *MockOMSUpdater_Update_Call) Run(run func(ctx context.Context, current string, repo selfupdate.Repository)) *MockOMSUpdater_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 selfupdate.Repository
		if args[2] != nil {
			arg2 = args[2].(selfupdate.Repository)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOMSUpdater_Update_Call) Return(s string, s1 string, err error) *MockOMSUpdater_Update_Call {
	_c.Call.Return(s, s1, err)
	return _c
}

func (_c *MockOMSUpdater_Update_Call) RunAndReturn(run func(ctx context.Context, current string, repo selfupdate.Repository) (string, string, error)) *MockOMSUpdater_Update_Call {
	_c.Call.Return(run)
	return _c
}
