// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package node

import (
	mock "github.com/stretchr/testify/mock"
	"time"
)

// NewMockNodeManager creates a new instance of MockNodeManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNodeManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNodeManager {
	mock := &MockNodeManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNodeManager is an autogenerated mock type for the NodeManager type
type MockNodeManager struct {
	mock.Mock
}

type MockNodeManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNodeManager) EXPECT() *MockNodeManager_Expecter {
	return &MockNodeManager_Expecter{mock: &_m.Mock}
}

// ConfigureAcceptEnv provides a mock function for the type MockNodeManager
func (_mock *MockNodeManager) ConfigureAcceptEnv() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ConfigureAcceptEnv")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNodeManager_ConfigureAcceptEnv_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfigureAcceptEnv'
type MockNodeManager_ConfigureAcceptEnv_Call struct {
	*mock.Call
}

// ConfigureAcceptEnv is a helper method to define mock.On call
func (_e *MockNodeManager_Expecter) ConfigureAcceptEnv() *MockNodeManager_ConfigureAcceptEnv_Call {
	return &MockNodeManager_ConfigureAcceptEnv_Call{Call: _e.mock.On("ConfigureAcceptEnv")}
}

func (_c *MockNodeManager_ConfigureAcceptEnv_Call) Run(run func()) *MockNodeManager_ConfigureAcceptEnv_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNodeManager_ConfigureAcceptEnv_Call) Return(err error) *MockNodeManager_ConfigureAcceptEnv_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNodeManager_ConfigureAcceptEnv_Call) RunAndReturn(run func() error) *MockNodeManager_ConfigureAcceptEnv_Call {
	_c.Call.Return(run)
	return _c
}

// ConfigureInotifyWatches provides a mock function for the type MockNodeManager
func (_mock *MockNodeManager) ConfigureInotifyWatches() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ConfigureInotifyWatches")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNodeManager_ConfigureInotifyWatches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfigureInotifyWatches'
type MockNodeManager_ConfigureInotifyWatches_Call struct {
	*mock.Call
}

// ConfigureInotifyWatches is a helper method to define mock.On call
func (_e *MockNodeManager_Expecter) ConfigureInotifyWatches() *MockNodeManager_ConfigureInotifyWatches_Call {
	return &MockNodeManager_ConfigureInotifyWatches_Call{Call: _e.mock.On("ConfigureInotifyWatches")}
}

func (_c *MockNodeManager_ConfigureInotifyWatches_Call) Run(run func()) *MockNodeManager_ConfigureInotifyWatches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNodeManager_ConfigureInotifyWatches_Call) Return(err error) *MockNodeManager_ConfigureInotifyWatches_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNodeManager_ConfigureInotifyWatches_Call) RunAndReturn(run func() error) *MockNodeManager_ConfigureInotifyWatches_Call {
	_c.Call.Return(run)
	return _c
}

// ConfigureMemoryMap provides a mock function for the type MockNodeManager
func (_mock *MockNodeManager) ConfigureMemoryMap() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ConfigureMemoryMap")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNodeManager_ConfigureMemoryMap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfigureMemoryMap'
type MockNodeManager_ConfigureMemoryMap_Call struct {
	*mock.Call
}

// ConfigureMemoryMap is a helper method to define mock.On call
func (_e *MockNodeManager_Expecter) ConfigureMemoryMap() *MockNodeManager_ConfigureMemoryMap_Call {
	return &MockNodeManager_ConfigureMemoryMap_Call{Call: _e.mock.On("ConfigureMemoryMap")}
}

func (_c *MockNodeManager_ConfigureMemoryMap_Call) Run(run func()) *MockNodeManager_ConfigureMemoryMap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNodeManager_ConfigureMemoryMap_Call) Return(err error) *MockNodeManager_ConfigureMemoryMap_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNodeManager_ConfigureMemoryMap_Call) RunAndReturn(run func() error) *MockNodeManager_ConfigureMemoryMap_Call {
	_c.Call.Return(run)
	return _c
}

// CopyFile provides a mock function for the type MockNodeManager
func (_mock *MockNodeManager) CopyFile(src string, dst string) error {
	ret := _mock.Called(src, dst)

	if len(ret) == 0 {
		panic("no return value specified for CopyFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(src, dst)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNodeManager_CopyFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CopyFile'
type MockNodeManager_CopyFile_Call struct {
	*mock.Call
}

// CopyFile is a helper method to define mock.On call
//   - src
//   - dst
func (_e *MockNodeManager_Expecter) CopyFile(src interface{}, dst interface{}) *MockNodeManager_CopyFile_Call {
	return &MockNodeManager_CopyFile_Call{Call: _e.mock.On("CopyFile", src, dst)}
}

func (_c *MockNodeManager_CopyFile_Call) Run(run func(src string, dst string)) *MockNodeManager_CopyFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockNodeManager_CopyFile_Call) Return(err error) *MockNodeManager_CopyFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNodeManager_CopyFile_Call) RunAndReturn(run func(src string, dst string) error) *MockNodeManager_CopyFile_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSubNode provides a mock function for the type MockNodeManager
func (_mock *MockNodeManager) CreateSubNode(name string, externalIP string, internalIP string) NodeManager {
	ret := _mock.Called(name, externalIP, internalIP)

	if len(ret) == 0 {
		panic("no return value specified for CreateSubNode")
	}

	var r0 NodeManager
	if returnFunc, ok := ret.Get(0).(func(string, string, string) NodeManager); ok {
		r0 = returnFunc(name, externalIP, internalIP)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(NodeManager)
		}
	}
	return r0
}

// MockNodeManager_CreateSubNode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSubNode'
type MockNodeManager_CreateSubNode_Call struct {
	*mock.Call
}

// CreateSubNode is a helper method to define mock.On call
//   - name
//   - externalIP
//   - internalIP
func (_e *MockNodeManager_Expecter) CreateSubNode(name interface{}, externalIP interface{}, internalIP interface{}) *MockNodeManager_CreateSubNode_Call {
	return &MockNodeManager_CreateSubNode_Call{Call: _e.mock.On("CreateSubNode", name, externalIP, internalIP)}
}

func (_c *MockNodeManager_CreateSubNode_Call) Run(run func(name string, externalIP string, internalIP string)) *MockNodeManager_CreateSubNode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockNodeManager_CreateSubNode_Call) Return(nodeManager NodeManager) *MockNodeManager_CreateSubNode_Call {
	_c.Call.Return(nodeManager)
	return _c
}

func (_c *MockNodeManager_CreateSubNode_Call) RunAndReturn(run func(name string, externalIP string, internalIP string) NodeManager) *MockNodeManager_CreateSubNode_Call {
	_c.Call.Return(run)
	return _c
}

// EnableRootLogin provides a mock function for the type MockNodeManager
func (_mock *MockNodeManager) EnableRootLogin() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for EnableRootLogin")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNodeManager_EnableRootLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnableRootLogin'
type MockNodeManager_EnableRootLogin_Call struct {
	*mock.Call
}

// EnableRootLogin is a helper method to define mock.On call
func (_e *MockNodeManager_Expecter) EnableRootLogin() *MockNodeManager_EnableRootLogin_Call {
	return &MockNodeManager_EnableRootLogin_Call{Call: _e.mock.On("EnableRootLogin")}
}

func (_c *MockNodeManager_EnableRootLogin_Call) Run(run func()) *MockNodeManager_EnableRootLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNodeManager_EnableRootLogin_Call) Return(err error) *MockNodeManager_EnableRootLogin_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNodeManager_EnableRootLogin_Call) RunAndReturn(run func() error) *MockNodeManager_EnableRootLogin_Call {
	_c.Call.Return(run)
	return _c
}

// GetExternalIP provides a mock function for the type MockNodeManager
func (_mock *MockNodeManager) GetExternalIP() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetExternalIP")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockNodeManager_GetExternalIP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExternalIP'
type MockNodeManager_GetExternalIP_Call struct {
	*mock.Call
}

// GetExternalIP is a helper method to define mock.On call
func (_e *MockNodeManager_Expecter) GetExternalIP() *MockNodeManager_GetExternalIP_Call {
	return &MockNodeManager_GetExternalIP_Call{Call: _e.mock.On("GetExternalIP")}
}

func (_c *MockNodeManager_GetExternalIP_Call) Run(run func()) *MockNodeManager_GetExternalIP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNodeManager_GetExternalIP_Call) Return(s string) *MockNodeManager_GetExternalIP_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockNodeManager_GetExternalIP_Call) RunAndReturn(run func() string) *MockNodeManager_GetExternalIP_Call {
	_c.Call.Return(run)
	return _c
}

// GetInternalIP provides a mock function for the type MockNodeManager
func (_mock *MockNodeManager) GetInternalIP() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetInternalIP")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockNodeManager_GetInternalIP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInternalIP'
type MockNodeManager_GetInternalIP_Call struct {
	*mock.Call
}

// GetInternalIP is a helper method to define mock.On call
func (_e *MockNodeManager_Expecter) GetInternalIP() *MockNodeManager_GetInternalIP_Call {
	return &MockNodeManager_GetInternalIP_Call{Call: _e.mock.On("GetInternalIP")}
}

func (_c *MockNodeManager_GetInternalIP_Call) Run(run func()) *MockNodeManager_GetInternalIP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNodeManager_GetInternalIP_Call) Return(s string) *MockNodeManager_GetInternalIP_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockNodeManager_GetInternalIP_Call) RunAndReturn(run func() string) *MockNodeManager_GetInternalIP_Call {
	_c.Call.Return(run)
	return _c
}

// GetName provides a mock function for the type MockNodeManager
func (_mock *MockNodeManager) GetName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockNodeManager_GetName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetName'
type MockNodeManager_GetName_Call struct {
	*mock.Call
}

// GetName is a helper method to define mock.On call
func (_e *MockNodeManager_Expecter) GetName() *MockNodeManager_GetName_Call {
	return &MockNodeManager_GetName_Call{Call: _e.mock.On("GetName")}
}

func (_c *MockNodeManager_GetName_Call) Run(run func()) *MockNodeManager_GetName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNodeManager_GetName_Call) Return(s string) *MockNodeManager_GetName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockNodeManager_GetName_Call) RunAndReturn(run func() string) *MockNodeManager_GetName_Call {
	_c.Call.Return(run)
	return _c
}

// HasAcceptEnvConfigured provides a mock function for the type MockNodeManager
func (_mock *MockNodeManager) HasAcceptEnvConfigured() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for HasAcceptEnvConfigured")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockNodeManager_HasAcceptEnvConfigured_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasAcceptEnvConfigured'
type MockNodeManager_HasAcceptEnvConfigured_Call struct {
	*mock.Call
}

// HasAcceptEnvConfigured is a helper method to define mock.On call
func (_e *MockNodeManager_Expecter) HasAcceptEnvConfigured() *MockNodeManager_HasAcceptEnvConfigured_Call {
	return &MockNodeManager_HasAcceptEnvConfigured_Call{Call: _e.mock.On("HasAcceptEnvConfigured")}
}

func (_c *MockNodeManager_HasAcceptEnvConfigured_Call) Run(run func()) *MockNodeManager_HasAcceptEnvConfigured_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNodeManager_HasAcceptEnvConfigured_Call) Return(b bool) *MockNodeManager_HasAcceptEnvConfigured_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockNodeManager_HasAcceptEnvConfigured_Call) RunAndReturn(run func() bool) *MockNodeManager_HasAcceptEnvConfigured_Call {
	_c.Call.Return(run)
	return _c
}

// HasCommand provides a mock function for the type MockNodeManager
func (_mock *MockNodeManager) HasCommand(command string) bool {
	ret := _mock.Called(command)

	if len(ret) == 0 {
		panic("no return value specified for HasCommand")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(command)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockNodeManager_HasCommand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasCommand'
type MockNodeManager_HasCommand_Call struct {
	*mock.Call
}

// HasCommand is a helper method to define mock.On call
//   - command
func (_e *MockNodeManager_Expecter) HasCommand(command interface{}) *MockNodeManager_HasCommand_Call {
	return &MockNodeManager_HasCommand_Call{Call: _e.mock.On("HasCommand", command)}
}

func (_c *MockNodeManager_HasCommand_Call) Run(run func(command string)) *MockNodeManager_HasCommand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockNodeManager_HasCommand_Call) Return(b bool) *MockNodeManager_HasCommand_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockNodeManager_HasCommand_Call) RunAndReturn(run func(command string) bool) *MockNodeManager_HasCommand_Call {
	_c.Call.Return(run)
	return _c
}

// HasFile provides a mock function for the type MockNodeManager
func (_mock *MockNodeManager) HasFile(filePath string) bool {
	ret := _mock.Called(filePath)

	if len(ret) == 0 {
		panic("no return value specified for HasFile")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(filePath)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockNodeManager_HasFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasFile'
type MockNodeManager_HasFile_Call struct {
	*mock.Call
}

// HasFile is a helper method to define mock.On call
//   - filePath
func (_e *MockNodeManager_Expecter) HasFile(filePath interface{}) *MockNodeManager_HasFile_Call {
	return &MockNodeManager_HasFile_Call{Call: _e.mock.On("HasFile", filePath)}
}

func (_c *MockNodeManager_HasFile_Call) Run(run func(filePath string)) *MockNodeManager_HasFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockNodeManager_HasFile_Call) Return(b bool) *MockNodeManager_HasFile_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockNodeManager_HasFile_Call) RunAndReturn(run func(filePath string) bool) *MockNodeManager_HasFile_Call {
	_c.Call.Return(run)
	return _c
}

// HasInotifyWatchesConfigured provides a mock function for the type MockNodeManager
func (_mock *MockNodeManager) HasInotifyWatchesConfigured() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for HasInotifyWatchesConfigured")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockNodeManager_HasInotifyWatchesConfigured_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasInotifyWatchesConfigured'
type MockNodeManager_HasInotifyWatchesConfigured_Call struct {
	*mock.Call
}

// HasInotifyWatchesConfigured is a helper method to define mock.On call
func (_e *MockNodeManager_Expecter) HasInotifyWatchesConfigured() *MockNodeManager_HasInotifyWatchesConfigured_Call {
	return &MockNodeManager_HasInotifyWatchesConfigured_Call{Call: _e.mock.On("HasInotifyWatchesConfigured")}
}

func (_c *MockNodeManager_HasInotifyWatchesConfigured_Call) Run(run func()) *MockNodeManager_HasInotifyWatchesConfigured_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNodeManager_HasInotifyWatchesConfigured_Call) Return(b bool) *MockNodeManager_HasInotifyWatchesConfigured_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockNodeManager_HasInotifyWatchesConfigured_Call) RunAndReturn(run func() bool) *MockNodeManager_HasInotifyWatchesConfigured_Call {
	_c.Call.Return(run)
	return _c
}

// HasMemoryMapConfigured provides a mock function for the type MockNodeManager
func (_mock *MockNodeManager) HasMemoryMapConfigured() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for HasMemoryMapConfigured")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockNodeManager_HasMemoryMapConfigured_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasMemoryMapConfigured'
type MockNodeManager_HasMemoryMapConfigured_Call struct {
	*mock.Call
}

// HasMemoryMapConfigured is a helper method to define mock.On call
func (_e *MockNodeManager_Expecter) HasMemoryMapConfigured() *MockNodeManager_HasMemoryMapConfigured_Call {
	return &MockNodeManager_HasMemoryMapConfigured_Call{Call: _e.mock.On("HasMemoryMapConfigured")}
}

func (_c *MockNodeManager_HasMemoryMapConfigured_Call) Run(run func()) *MockNodeManager_HasMemoryMapConfigured_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNodeManager_HasMemoryMapConfigured_Call) Return(b bool) *MockNodeManager_HasMemoryMapConfigured_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockNodeManager_HasMemoryMapConfigured_Call) RunAndReturn(run func() bool) *MockNodeManager_HasMemoryMapConfigured_Call {
	_c.Call.Return(run)
	return _c
}

// HasRootLoginEnabled provides a mock function for the type MockNodeManager
func (_mock *MockNodeManager) HasRootLoginEnabled() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for HasRootLoginEnabled")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockNodeManager_HasRootLoginEnabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasRootLoginEnabled'
type MockNodeManager_HasRootLoginEnabled_Call struct {
	*mock.Call
}

// HasRootLoginEnabled is a helper method to define mock.On call
func (_e *MockNodeManager_Expecter) HasRootLoginEnabled() *MockNodeManager_HasRootLoginEnabled_Call {
	return &MockNodeManager_HasRootLoginEnabled_Call{Call: _e.mock.On("HasRootLoginEnabled")}
}

func (_c *MockNodeManager_HasRootLoginEnabled_Call) Run(run func()) *MockNodeManager_HasRootLoginEnabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNodeManager_HasRootLoginEnabled_Call) Return(b bool) *MockNodeManager_HasRootLoginEnabled_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockNodeManager_HasRootLoginEnabled_Call) RunAndReturn(run func() bool) *MockNodeManager_HasRootLoginEnabled_Call {
	_c.Call.Return(run)
	return _c
}

// InstallOms provides a mock function for the type MockNodeManager
func (_mock *MockNodeManager) InstallOms() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for InstallOms")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNodeManager_InstallOms_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InstallOms'
type MockNodeManager_InstallOms_Call struct {
	*mock.Call
}

// InstallOms is a helper method to define mock.On call
func (_e *MockNodeManager_Expecter) InstallOms() *MockNodeManager_InstallOms_Call {
	return &MockNodeManager_InstallOms_Call{Call: _e.mock.On("InstallOms")}
}

func (_c *MockNodeManager_InstallOms_Call) Run(run func()) *MockNodeManager_InstallOms_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNodeManager_InstallOms_Call) Return(err error) *MockNodeManager_InstallOms_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNodeManager_InstallOms_Call) RunAndReturn(run func() error) *MockNodeManager_InstallOms_Call {
	_c.Call.Return(run)
	return _c
}

// RunSSHCommand provides a mock function for the type MockNodeManager
func (_mock *MockNodeManager) RunSSHCommand(username string, command string, quiet bool) error {
	ret := _mock.Called(username, command, quiet)

	if len(ret) == 0 {
		panic("no return value specified for RunSSHCommand")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, bool) error); ok {
		r0 = returnFunc(username, command, quiet)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNodeManager_RunSSHCommand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunSSHCommand'
type MockNodeManager_RunSSHCommand_Call struct {
	*mock.Call
}

// RunSSHCommand is a helper method to define mock.On call
//   - username
//   - command
//   - quiet
func (_e *MockNodeManager_Expecter) RunSSHCommand(username interface{}, command interface{}, quiet interface{}) *MockNodeManager_RunSSHCommand_Call {
	return &MockNodeManager_RunSSHCommand_Call{Call: _e.mock.On("RunSSHCommand", username, command, quiet)}
}

func (_c *MockNodeManager_RunSSHCommand_Call) Run(run func(username string, command string, quiet bool)) *MockNodeManager_RunSSHCommand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(bool))
	})
	return _c
}

func (_c *MockNodeManager_RunSSHCommand_Call) Return(err error) *MockNodeManager_RunSSHCommand_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNodeManager_RunSSHCommand_Call) RunAndReturn(run func(username string, command string, quiet bool) error) *MockNodeManager_RunSSHCommand_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateNode provides a mock function for the type MockNodeManager
func (_mock *MockNodeManager) UpdateNode(name string, externalIP string, internalIP string) {
	_mock.Called(name, externalIP, internalIP)
	return
}

// MockNodeManager_UpdateNode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateNode'
type MockNodeManager_UpdateNode_Call struct {
	*mock.Call
}

// UpdateNode is a helper method to define mock.On call
//   - name
//   - externalIP
//   - internalIP
func (_e *MockNodeManager_Expecter) UpdateNode(name interface{}, externalIP interface{}, internalIP interface{}) *MockNodeManager_UpdateNode_Call {
	return &MockNodeManager_UpdateNode_Call{Call: _e.mock.On("UpdateNode", name, externalIP, internalIP)}
}

func (_c *MockNodeManager_UpdateNode_Call) Run(run func(name string, externalIP string, internalIP string)) *MockNodeManager_UpdateNode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockNodeManager_UpdateNode_Call) Return() *MockNodeManager_UpdateNode_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockNodeManager_UpdateNode_Call) RunAndReturn(run func(name string, externalIP string, internalIP string)) *MockNodeManager_UpdateNode_Call {
	_c.Run(run)
	return _c
}

// WaitForSSH provides a mock function for the type MockNodeManager
func (_mock *MockNodeManager) WaitForSSH(timeout time.Duration) error {
	ret := _mock.Called(timeout)

	if len(ret) == 0 {
		panic("no return value specified for WaitForSSH")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(time.Duration) error); ok {
		r0 = returnFunc(timeout)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNodeManager_WaitForSSH_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitForSSH'
type MockNodeManager_WaitForSSH_Call struct {
	*mock.Call
}

// WaitForSSH is a helper method to define mock.On call
//   - timeout
func (_e *MockNodeManager_Expecter) WaitForSSH(timeout interface{}) *MockNodeManager_WaitForSSH_Call {
	return &MockNodeManager_WaitForSSH_Call{Call: _e.mock.On("WaitForSSH", timeout)}
}

func (_c *MockNodeManager_WaitForSSH_Call) Run(run func(timeout time.Duration)) *MockNodeManager_WaitForSSH_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(time.Duration))
	})
	return _c
}

func (_c *MockNodeManager_WaitForSSH_Call) Return(err error) *MockNodeManager_WaitForSSH_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNodeManager_WaitForSSH_Call) RunAndReturn(run func(timeout time.Duration) error) *MockNodeManager_WaitForSSH_Call {
	_c.Call.Return(run)
	return _c
}
