// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package util

import (
	"github.com/jedib0t/go-pretty/v6/table"
	mock "github.com/stretchr/testify/mock"
	"os"
)

// NewMockFileIO creates a new instance of MockFileIO. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileIO(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileIO {
	mock := &MockFileIO{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFileIO is an autogenerated mock type for the FileIO type
type MockFileIO struct {
	mock.Mock
}

type MockFileIO_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileIO) EXPECT() *MockFileIO_Expecter {
	return &MockFileIO_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockFileIO
func (_mock *MockFileIO) Create(filename string) (*os.File, error) {
	ret := _mock.Called(filename)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *os.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*os.File, error)); ok {
		return returnFunc(filename)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *os.File); ok {
		r0 = returnFunc(filename)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*os.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(filename)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileIO_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockFileIO_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - filename
func (_e *MockFileIO_Expecter) Create(filename interface{}) *MockFileIO_Create_Call {
	return &MockFileIO_Create_Call{Call: _e.mock.On("Create", filename)}
}

func (_c *MockFileIO_Create_Call) Run(run func(filename string)) *MockFileIO_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockFileIO_Create_Call) Return(file *os.File, err error) *MockFileIO_Create_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *MockFileIO_Create_Call) RunAndReturn(run func(filename string) (*os.File, error)) *MockFileIO_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function for the type MockFileIO
func (_mock *MockFileIO) Exists(filename string) bool {
	ret := _mock.Called(filename)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(filename)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockFileIO_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockFileIO_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - filename
func (_e *MockFileIO_Expecter) Exists(filename interface{}) *MockFileIO_Exists_Call {
	return &MockFileIO_Exists_Call{Call: _e.mock.On("Exists", filename)}
}

func (_c *MockFileIO_Exists_Call) Run(run func(filename string)) *MockFileIO_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockFileIO_Exists_Call) Return(b bool) *MockFileIO_Exists_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockFileIO_Exists_Call) RunAndReturn(run func(filename string) bool) *MockFileIO_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// IsDirectory provides a mock function for the type MockFileIO
func (_mock *MockFileIO) IsDirectory(filename string) (bool, error) {
	ret := _mock.Called(filename)

	if len(ret) == 0 {
		panic("no return value specified for IsDirectory")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return returnFunc(filename)
	}
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(filename)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(filename)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileIO_IsDirectory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsDirectory'
type MockFileIO_IsDirectory_Call struct {
	*mock.Call
}

// IsDirectory is a helper method to define mock.On call
//   - filename
func (_e *MockFileIO_Expecter) IsDirectory(filename interface{}) *MockFileIO_IsDirectory_Call {
	return &MockFileIO_IsDirectory_Call{Call: _e.mock.On("IsDirectory", filename)}
}

func (_c *MockFileIO_IsDirectory_Call) Run(run func(filename string)) *MockFileIO_IsDirectory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockFileIO_IsDirectory_Call) Return(b bool, err error) *MockFileIO_IsDirectory_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockFileIO_IsDirectory_Call) RunAndReturn(run func(filename string) (bool, error)) *MockFileIO_IsDirectory_Call {
	_c.Call.Return(run)
	return _c
}

// MkdirAll provides a mock function for the type MockFileIO
func (_mock *MockFileIO) MkdirAll(path string, perm os.FileMode) error {
	ret := _mock.Called(path, perm)

	if len(ret) == 0 {
		panic("no return value specified for MkdirAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, os.FileMode) error); ok {
		r0 = returnFunc(path, perm)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileIO_MkdirAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MkdirAll'
type MockFileIO_MkdirAll_Call struct {
	*mock.Call
}

// MkdirAll is a helper method to define mock.On call
//   - path
//   - perm
func (_e *MockFileIO_Expecter) MkdirAll(path interface{}, perm interface{}) *MockFileIO_MkdirAll_Call {
	return &MockFileIO_MkdirAll_Call{Call: _e.mock.On("MkdirAll", path, perm)}
}

func (_c *MockFileIO_MkdirAll_Call) Run(run func(path string, perm os.FileMode)) *MockFileIO_MkdirAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(os.FileMode))
	})
	return _c
}

func (_c *MockFileIO_MkdirAll_Call) Return(err error) *MockFileIO_MkdirAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileIO_MkdirAll_Call) RunAndReturn(run func(path string, perm os.FileMode) error) *MockFileIO_MkdirAll_Call {
	_c.Call.Return(run)
	return _c
}

// Open provides a mock function for the type MockFileIO
func (_mock *MockFileIO) Open(filename string) (*os.File, error) {
	ret := _mock.Called(filename)

	if len(ret) == 0 {
		panic("no return value specified for Open")
	}

	var r0 *os.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*os.File, error)); ok {
		return returnFunc(filename)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *os.File); ok {
		r0 = returnFunc(filename)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*os.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(filename)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileIO_Open_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Open'
type MockFileIO_Open_Call struct {
	*mock.Call
}

// Open is a helper method to define mock.On call
//   - filename
func (_e *MockFileIO_Expecter) Open(filename interface{}) *MockFileIO_Open_Call {
	return &MockFileIO_Open_Call{Call: _e.mock.On("Open", filename)}
}

func (_c *MockFileIO_Open_Call) Run(run func(filename string)) *MockFileIO_Open_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockFileIO_Open_Call) Return(file *os.File, err error) *MockFileIO_Open_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *MockFileIO_Open_Call) RunAndReturn(run func(filename string) (*os.File, error)) *MockFileIO_Open_Call {
	_c.Call.Return(run)
	return _c
}

// OpenFile provides a mock function for the type MockFileIO
func (_mock *MockFileIO) OpenFile(name string, flag int, perm os.FileMode) (*os.File, error) {
	ret := _mock.Called(name, flag, perm)

	if len(ret) == 0 {
		panic("no return value specified for OpenFile")
	}

	var r0 *os.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, int, os.FileMode) (*os.File, error)); ok {
		return returnFunc(name, flag, perm)
	}
	if returnFunc, ok := ret.Get(0).(func(string, int, os.FileMode) *os.File); ok {
		r0 = returnFunc(name, flag, perm)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*os.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, int, os.FileMode) error); ok {
		r1 = returnFunc(name, flag, perm)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileIO_OpenFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenFile'
type MockFileIO_OpenFile_Call struct {
	*mock.Call
}

// OpenFile is a helper method to define mock.On call
//   - name
//   - flag
//   - perm
func (_e *MockFileIO_Expecter) OpenFile(name interface{}, flag interface{}, perm interface{}) *MockFileIO_OpenFile_Call {
	return &MockFileIO_OpenFile_Call{Call: _e.mock.On("OpenFile", name, flag, perm)}
}

func (_c *MockFileIO_OpenFile_Call) Run(run func(name string, flag int, perm os.FileMode)) *MockFileIO_OpenFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int), args[2].(os.FileMode))
	})
	return _c
}

func (_c *MockFileIO_OpenFile_Call) Return(file *os.File, err error) *MockFileIO_OpenFile_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *MockFileIO_OpenFile_Call) RunAndReturn(run func(name string, flag int, perm os.FileMode) (*os.File, error)) *MockFileIO_OpenFile_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClosableFile creates a new instance of MockClosableFile. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClosableFile(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClosableFile {
	mock := &MockClosableFile{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClosableFile is an autogenerated mock type for the ClosableFile type
type MockClosableFile struct {
	mock.Mock
}

type MockClosableFile_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClosableFile) EXPECT() *MockClosableFile_Expecter {
	return &MockClosableFile_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockClosableFile
func (_mock *MockClosableFile) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClosableFile_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockClosableFile_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockClosableFile_Expecter) Close() *MockClosableFile_Close_Call {
	return &MockClosableFile_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockClosableFile_Close_Call) Run(run func()) *MockClosableFile_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClosableFile_Close_Call) Return(err error) *MockClosableFile_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClosableFile_Close_Call) RunAndReturn(run func() error) *MockClosableFile_Close_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTableWriter creates a new instance of MockTableWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTableWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTableWriter {
	mock := &MockTableWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTableWriter is an autogenerated mock type for the TableWriter type
type MockTableWriter struct {
	mock.Mock
}

type MockTableWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTableWriter) EXPECT() *MockTableWriter_Expecter {
	return &MockTableWriter_Expecter{mock: &_m.Mock}
}

// AppendHeader provides a mock function for the type MockTableWriter
func (_mock *MockTableWriter) AppendHeader(row table.Row, configs ...table.RowConfig) {
	if len(configs) > 0 {
		_mock.Called(row, configs)
	} else {
		_mock.Called(row)
	}

	return
}

// MockTableWriter_AppendHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AppendHeader'
type MockTableWriter_AppendHeader_Call struct {
	*mock.Call
}

// AppendHeader is a helper method to define mock.On call
//   - row
//   - configs
func (_e *MockTableWriter_Expecter) AppendHeader(row interface{}, configs ...interface{}) *MockTableWriter_AppendHeader_Call {
	return &MockTableWriter_AppendHeader_Call{Call: _e.mock.On("AppendHeader",
		append([]interface{}{row}, configs...)...)}
}

func (_c *MockTableWriter_AppendHeader_Call) Run(run func(row table.Row, configs ...table.RowConfig)) *MockTableWriter_AppendHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]table.RowConfig, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(table.RowConfig)
			}
		}
		run(args[0].(table.Row), variadicArgs...)
	})
	return _c
}

func (_c *MockTableWriter_AppendHeader_Call) Return() *MockTableWriter_AppendHeader_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTableWriter_AppendHeader_Call) RunAndReturn(run func(row table.Row, configs ...table.RowConfig)) *MockTableWriter_AppendHeader_Call {
	_c.Run(run)
	return _c
}

// AppendRow provides a mock function for the type MockTableWriter
func (_mock *MockTableWriter) AppendRow(row table.Row, configs ...table.RowConfig) {
	if len(configs) > 0 {
		_mock.Called(row, configs)
	} else {
		_mock.Called(row)
	}

	return
}

// MockTableWriter_AppendRow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AppendRow'
type MockTableWriter_AppendRow_Call struct {
	*mock.Call
}

// AppendRow is a helper method to define mock.On call
//   - row
//   - configs
func (_e *MockTableWriter_Expecter) AppendRow(row interface{}, configs ...interface{}) *MockTableWriter_AppendRow_Call {
	return &MockTableWriter_AppendRow_Call{Call: _e.mock.On("AppendRow",
		append([]interface{}{row}, configs...)...)}
}

func (_c *MockTableWriter_AppendRow_Call) Run(run func(row table.Row, configs ...table.RowConfig)) *MockTableWriter_AppendRow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]table.RowConfig, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(table.RowConfig)
			}
		}
		run(args[0].(table.Row), variadicArgs...)
	})
	return _c
}

func (_c *MockTableWriter_AppendRow_Call) Return() *MockTableWriter_AppendRow_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTableWriter_AppendRow_Call) RunAndReturn(run func(row table.Row, configs ...table.RowConfig)) *MockTableWriter_AppendRow_Call {
	_c.Run(run)
	return _c
}

// Render provides a mock function for the type MockTableWriter
func (_mock *MockTableWriter) Render() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Render")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTableWriter_Render_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Render'
type MockTableWriter_Render_Call struct {
	*mock.Call
}

// Render is a helper method to define mock.On call
func (_e *MockTableWriter_Expecter) Render() *MockTableWriter_Render_Call {
	return &MockTableWriter_Render_Call{Call: _e.mock.On("Render")}
}

func (_c *MockTableWriter_Render_Call) Run(run func()) *MockTableWriter_Render_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTableWriter_Render_Call) Return(s string) *MockTableWriter_Render_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTableWriter_Render_Call) RunAndReturn(run func() string) *MockTableWriter_Render_Call {
	_c.Call.Return(run)
	return _c
}
