// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package codesphere

import (
	"context"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// CreateWorkspace provides a mock function for the type MockClient
func (_mock *MockClient) CreateWorkspace(ctx context.Context, teamID int, planID int, name string, repoURL *string) (int, error) {
	ret := _mock.Called(ctx, teamID, planID, name, repoURL)

	if len(ret) == 0 {
		panic("no return value specified for CreateWorkspace")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, string, *string) (int, error)); ok {
		return returnFunc(ctx, teamID, planID, name, repoURL)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, string, *string) int); ok {
		r0 = returnFunc(ctx, teamID, planID, name, repoURL)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int, string, *string) error); ok {
		r1 = returnFunc(ctx, teamID, planID, name, repoURL)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_CreateWorkspace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWorkspace'
type MockClient_CreateWorkspace_Call struct {
	*mock.Call
}

// CreateWorkspace is a helper method to define mock.On call
//   - ctx
//   - teamID
//   - planID
//   - name
//   - repoURL
func (_e *MockClient_Expecter) CreateWorkspace(ctx interface{}, teamID interface{}, planID interface{}, name interface{}, repoURL interface{}) *MockClient_CreateWorkspace_Call {
	return &MockClient_CreateWorkspace_Call{Call: _e.mock.On("CreateWorkspace", ctx, teamID, planID, name, repoURL)}
}

func (_c *MockClient_CreateWorkspace_Call) Run(run func(ctx context.Context, teamID int, planID int, name string, repoURL *string)) *MockClient_CreateWorkspace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int), args[3].(string), args[4].(*string))
	})
	return _c
}

func (_c *MockClient_CreateWorkspace_Call) Return(workspaceID int, err error) *MockClient_CreateWorkspace_Call {
	_c.Call.Return(workspaceID, err)
	return _c
}

func (_c *MockClient_CreateWorkspace_Call) RunAndReturn(run func(ctx context.Context, teamID int, planID int, name string, repoURL *string) (int, error)) *MockClient_CreateWorkspace_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteWorkspace provides a mock function for the type MockClient
func (_mock *MockClient) DeleteWorkspace(ctx context.Context, workspaceID int) error {
	ret := _mock.Called(ctx, workspaceID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteWorkspace")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, workspaceID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_DeleteWorkspace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteWorkspace'
type MockClient_DeleteWorkspace_Call struct {
	*mock.Call
}

// DeleteWorkspace is a helper method to define mock.On call
//   - ctx
//   - workspaceID
func (_e *MockClient_Expecter) DeleteWorkspace(ctx interface{}, workspaceID interface{}) *MockClient_DeleteWorkspace_Call {
	return &MockClient_DeleteWorkspace_Call{Call: _e.mock.On("DeleteWorkspace", ctx, workspaceID)}
}

func (_c *MockClient_DeleteWorkspace_Call) Run(run func(ctx context.Context, workspaceID int)) *MockClient_DeleteWorkspace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockClient_DeleteWorkspace_Call) Return(err error) *MockClient_DeleteWorkspace_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_DeleteWorkspace_Call) RunAndReturn(run func(ctx context.Context, workspaceID int) error) *MockClient_DeleteWorkspace_Call {
	_c.Call.Return(run)
	return _c
}

// ExecuteCommand provides a mock function for the type MockClient
func (_mock *MockClient) ExecuteCommand(ctx context.Context, workspaceID int, command string) error {
	ret := _mock.Called(ctx, workspaceID, command)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteCommand")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) error); ok {
		r0 = returnFunc(ctx, workspaceID, command)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_ExecuteCommand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteCommand'
type MockClient_ExecuteCommand_Call struct {
	*mock.Call
}

// ExecuteCommand is a helper method to define mock.On call
//   - ctx
//   - workspaceID
//   - command
func (_e *MockClient_Expecter) ExecuteCommand(ctx interface{}, workspaceID interface{}, command interface{}) *MockClient_ExecuteCommand_Call {
	return &MockClient_ExecuteCommand_Call{Call: _e.mock.On("ExecuteCommand", ctx, workspaceID, command)}
}

func (_c *MockClient_ExecuteCommand_Call) Run(run func(ctx context.Context, workspaceID int, command string)) *MockClient_ExecuteCommand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(string))
	})
	return _c
}

func (_c *MockClient_ExecuteCommand_Call) Return(err error) *MockClient_ExecuteCommand_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_ExecuteCommand_Call) RunAndReturn(run func(ctx context.Context, workspaceID int, command string) error) *MockClient_ExecuteCommand_Call {
	_c.Call.Return(run)
	return _c
}

// SetEnvVar provides a mock function for the type MockClient
func (_mock *MockClient) SetEnvVar(ctx context.Context, workspaceID int, key string, value string) error {
	ret := _mock.Called(ctx, workspaceID, key, value)

	if len(ret) == 0 {
		panic("no return value specified for SetEnvVar")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string, string) error); ok {
		r0 = returnFunc(ctx, workspaceID, key, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_SetEnvVar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetEnvVar'
type MockClient_SetEnvVar_Call struct {
	*mock.Call
}

// SetEnvVar is a helper method to define mock.On call
//   - ctx
//   - workspaceID
//   - key
//   - value
func (_e *MockClient_Expecter) SetEnvVar(ctx interface{}, workspaceID interface{}, key interface{}, value interface{}) *MockClient_SetEnvVar_Call {
	return &MockClient_SetEnvVar_Call{Call: _e.mock.On("SetEnvVar", ctx, workspaceID, key, value)}
}

func (_c *MockClient_SetEnvVar_Call) Run(run func(ctx context.Context, workspaceID int, key string, value string)) *MockClient_SetEnvVar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockClient_SetEnvVar_Call) Return(err error) *MockClient_SetEnvVar_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_SetEnvVar_Call) RunAndReturn(run func(ctx context.Context, workspaceID int, key string, value string) error) *MockClient_SetEnvVar_Call {
	_c.Call.Return(run)
	return _c
}

// StartPipeline provides a mock function for the type MockClient
func (_mock *MockClient) StartPipeline(ctx context.Context, workspaceID int, profile string, stage string) error {
	ret := _mock.Called(ctx, workspaceID, profile, stage)

	if len(ret) == 0 {
		panic("no return value specified for StartPipeline")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string, string) error); ok {
		r0 = returnFunc(ctx, workspaceID, profile, stage)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_StartPipeline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartPipeline'
type MockClient_StartPipeline_Call struct {
	*mock.Call
}

// StartPipeline is a helper method to define mock.On call
//   - ctx
//   - workspaceID
//   - profile
//   - stage
func (_e *MockClient_Expecter) StartPipeline(ctx interface{}, workspaceID interface{}, profile interface{}, stage interface{}) *MockClient_StartPipeline_Call {
	return &MockClient_StartPipeline_Call{Call: _e.mock.On("StartPipeline", ctx, workspaceID, profile, stage)}
}

func (_c *MockClient_StartPipeline_Call) Run(run func(ctx context.Context, workspaceID int, profile string, stage string)) *MockClient_StartPipeline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockClient_StartPipeline_Call) Return(err error) *MockClient_StartPipeline_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_StartPipeline_Call) RunAndReturn(run func(ctx context.Context, workspaceID int, profile string, stage string) error) *MockClient_StartPipeline_Call {
	_c.Call.Return(run)
	return _c
}

// SyncLandscape provides a mock function for the type MockClient
func (_mock *MockClient) SyncLandscape(ctx context.Context, workspaceID int, profile string) error {
	ret := _mock.Called(ctx, workspaceID, profile)

	if len(ret) == 0 {
		panic("no return value specified for SyncLandscape")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) error); ok {
		r0 = returnFunc(ctx, workspaceID, profile)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_SyncLandscape_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncLandscape'
type MockClient_SyncLandscape_Call struct {
	*mock.Call
}

// SyncLandscape is a helper method to define mock.On call
//   - ctx
//   - workspaceID
//   - profile
func (_e *MockClient_Expecter) SyncLandscape(ctx interface{}, workspaceID interface{}, profile interface{}) *MockClient_SyncLandscape_Call {
	return &MockClient_SyncLandscape_Call{Call: _e.mock.On("SyncLandscape", ctx, workspaceID, profile)}
}

func (_c *MockClient_SyncLandscape_Call) Run(run func(ctx context.Context, workspaceID int, profile string)) *MockClient_SyncLandscape_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(string))
	})
	return _c
}

func (_c *MockClient_SyncLandscape_Call) Return(err error) *MockClient_SyncLandscape_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_SyncLandscape_Call) RunAndReturn(run func(ctx context.Context, workspaceID int, profile string) error) *MockClient_SyncLandscape_Call {
	_c.Call.Return(run)
	return _c
}
