// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package teststeps

import (
	"context"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSmokeTestStep creates a new instance of MockSmokeTestStep. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSmokeTestStep(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSmokeTestStep {
	mock := &MockSmokeTestStep{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSmokeTestStep is an autogenerated mock type for the SmokeTestStep type
type MockSmokeTestStep struct {
	mock.Mock
}

type MockSmokeTestStep_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSmokeTestStep) EXPECT() *MockSmokeTestStep_Expecter {
	return &MockSmokeTestStep_Expecter{mock: &_m.Mock}
}

// Name provides a mock function for the type MockSmokeTestStep
func (_mock *MockSmokeTestStep) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockSmokeTestStep_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockSmokeTestStep_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockSmokeTestStep_Expecter) Name() *MockSmokeTestStep_Name_Call {
	return &MockSmokeTestStep_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockSmokeTestStep_Name_Call) Run(run func()) *MockSmokeTestStep_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSmokeTestStep_Name_Call) Return(s string) *MockSmokeTestStep_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockSmokeTestStep_Name_Call) RunAndReturn(run func() string) *MockSmokeTestStep_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function for the type MockSmokeTestStep
func (_mock *MockSmokeTestStep) Run(ctx context.Context, c *SmoketestCodesphereOpts, workspaceID *int) error {
	ret := _mock.Called(ctx, c, workspaceID)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *SmoketestCodesphereOpts, *int) error); ok {
		r0 = returnFunc(ctx, c, workspaceID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSmokeTestStep_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockSmokeTestStep_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - c *SmoketestCodesphereOpts
//   - workspaceID *int
func (_e *MockSmokeTestStep_Expecter) Run(ctx interface{}, c interface{}, workspaceID interface{}) *MockSmokeTestStep_Run_Call {
	return &MockSmokeTestStep_Run_Call{Call: _e.mock.On("Run", ctx, c, workspaceID)}
}

func (_c *MockSmokeTestStep_Run_Call) Run(run func(ctx context.Context, c *SmoketestCodesphereOpts, workspaceID *int)) *MockSmokeTestStep_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *SmoketestCodesphereOpts
		if args[1] != nil {
			arg1 = args[1].(*SmoketestCodesphereOpts)
		}
		var arg2 *int
		if args[2] != nil {
			arg2 = args[2].(*int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSmokeTestStep_Run_Call) Return(err error) *MockSmokeTestStep_Run_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSmokeTestStep_Run_Call) RunAndReturn(run func(ctx context.Context, c *SmoketestCodesphereOpts, workspaceID *int) error) *MockSmokeTestStep_Run_Call {
	_c.Call.Return(run)
	return _c
}
