# Copyright (c) Codesphere Inc.
# SPDX-License-Identifier: Apache-2.0

# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build & Test CLI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          go-version-file: 'go.mod'

      - name: Build
        run: make build-cli

      - name: Slack Notification on Failure
        if: ${{ failure() && github.ref == 'refs/heads/main' }}
        run: |
          curl -X POST \
            -H 'Content-type: application/json' \
            --data '{
              "channel": "#team-oms-sdk",
              "icon_emoji": ":siren:",
              "text": "🚨 Build Job Failure 🚨\nRepository: ${{ github.repository }}\nBranch/Ref: `${{ github.ref }}`\nRun url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }' \
            ${{ secrets.PACKAGE_JOB_SLACK_WEBHOOK }}

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          go-version-file: 'go.mod'

      - name: Test
        run: make test

      - name: Slack Notification on Failure
        if: ${{ failure() && github.ref == 'refs/heads/main' }}
        run: |
          curl -X POST \
            -H 'Content-type: application/json' \
            --data '{
              "channel": "#team-oms-sdk",
              "icon_emoji": ":siren:",
              "text": "🚨 Build Job Failure 🚨\nRepository: ${{ github.repository }}\nBranch/Ref: `${{ github.ref }}`\nRun url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }' \
            ${{ secrets.PACKAGE_JOB_SLACK_WEBHOOK }}
