name: integration-tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          go-version-file: 'go.mod'

      - name: Build CLI
        run: make build-cli

      - name: Run Integration Tests
        env:
          OMS_PORTAL_API_KEY: ${{ secrets.OMS_PORTAL_API_KEY }}
          OMS_PORTAL_API: ${{ secrets.OMS_PORTAL_API }}
        run: make test-integration
