# Copyright (c) Codesphere Inc.
# SPDX-License-Identifier: Apache-2.0

name: Tag

on:
  push:
    branches:
      - main

jobs:
  integration-tests:
    uses: ./.github/workflows/integration-test.yml
    secrets: inherit

  tag:
    runs-on: ubuntu-latest
    needs: integration-tests
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6
        with:
          go-version-file: 'go.mod'

      - name: Tag
        run: hack/tag-release.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Slack Notification on Failure
        if: ${{ failure() }}
        run: |
          curl -X POST \
            -H 'Content-type: application/json' \
            --data '{
              "channel": "#team-oms-sdk",
              "icon_emoji": ":siren:",
              "text": "🚨 Release Job Failure 🚨\nRepository: ${{ github.repository }}\nBranch/Ref: `${{ github.ref }}`\nRun url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }' \
            ${{ secrets.PACKAGE_JOB_SLACK_WEBHOOK }}
