# Copyright (c) Codesphere Inc.
# SPDX-License-Identifier: Apache-2.0

name: 'Auto-Update Docs & Licenses'

permissions:
  contents: write

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  update-files:
    # skip runs triggered by the bot's own commit to avoid loops and runs triggered by renovate
    if: github.actor != 'github-actions[bot]' && !startsWith(github.event.pull_request.head.ref, 'renovate/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          # on push to main, use main; on PR, check out the PR head
          ref: ${{ github.event.pull_request.head.ref || github.ref }}
          # Use PAT to ensure commits trigger other workflows
          token: ${{ secrets.PAT_UPDATE_DOCS }}

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          go-version-file: 'go.mod'

      - name: Update docs & licenses
        run: |
          ./hack/update-docs-and-licenses.sh

      - name: Commit and push auto-generated changes
        uses: EndBug/add-and-commit@cc9c08ba6c8df3b93a8f2db63e89b98368ae2ae8 # v11
        with:
          # Use the PR author's identity for the commit
          author_name: ${{ github.event.pull_request.user.login }}
          author_email: ${{ github.event.pull_request.user.id }}+${{ github.event.pull_request.user.login }}@users.noreply.github.com
          
          # Commit message
          message: 'chore(docs): Auto-update docs and licenses'
          
          # Adds a sign-off to the commit message for DCO
          commit: '--signoff'
